#!/bin/bash

###########################
#(C) Will Cunningham 2017 #
#         DK Lab          #
# Northeastern University #
###########################

# Measure clustering distributions of various manifolds

set -eu -o pipefail

# GENERAL USE
# Use 'setnextjob' command
# Set spacetime
# Set density/degree
# Choose queue
# Choose age, nodes, and spatial cutoff

spacetime=4800144
density=60
#degree=10

if [[ "$spacetime" -eq 4800114 ]] ; then
  spacecut="radius"
else
  spacecut="alpha"
fi

if [[ -z ${degree+x} ]] ; then
  echo "Beginning constant density experiment."
  timecut=energy
else
  echo "Beginning constant degree experiment."
fi

source /home/$USER/.queues
jobstart=$NEXT_JOB
samples=10
partition="krioukov_gpu"
ncores=$(sinfo -p $partition -o "%c" | awk 'NR==2 {print $1}')
exclude="compute-0-000"

if [ "$partition" = "par-gpu" ] || [ "$partition" = "par-gpu-2" ] || [ "$partition" = "par-gpu-3" ] || [ "$partition" = "krioukov_gpu" ] ; then
  gpu="--gpu"
else
  gpu=""
fi

age=0.73

#nodes=122880
#cutoff=4.9997

#nodes=24832
#cutoff=5.9992

nodes=34048
cutoff=5.9887

$CAUSET_HOME/cluster/slurm/wrapper/causet_wrp --start $jobstart --ncores $ncores --flags '--spacetime '"$spacetime"' --nodes '"$nodes"' --'"$timecut"' '"$age"' --'"$spacecut"' '"$cutoff"' --link '"$gpu"' --verbose -y --print --print-edges --clustering' --partition $partition --nsamples $samples --exclude $exclude

setnextjob $(($jobstart+1))
