#!/bin/bash

stdim=4
manifold=desitter
region=slab
curvature=flat
symmetry=asymmetric
spacetime="--stdim $stdim --manifold $manifold --region $region --curvature $curvature --symmetry $symmetry"

nodes=122880
energy=0.73
radius=4.9997
constraints="--nodes $nodes --energy $energy --radius $radius"

link="--link --gpu"
measure="--success 1000 --stretch"
xtra="--verbose -y --seed 1478101616"

#flags="$spacetime $constraints $link $measure $xtra"
flags='--stdim 4 --manifold desitter --region slab --curvature flat --symmetry asymmetric --nodes 122880 --energy 0.73 --radius 4.9997 --link --gpu --success 1000 --stretch --verbose -y --seed 1478101616 --print'

source /home/$USER/.queues
job=$NEXT_JOB

$CAUSET_HOME/cluster/slurm/wrapper/causet_wrp -f "$flags" -p krioukov_gpu -c 48 -J $job -x compute-4-017

setnextjob $(($job+1))
