#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Number of jobs to run in parallel in separate nodes
njobs=1

# Job ID offset (used for naming directories)
jobstart=1

# Number of samples to run serially on a single node
nsamples=1

# Job ID used for reading existing graph data
readjobid=0

# Graph ID used for reading existing graph data
readgraphid=0

# Flags passed to CausalSet program
flags=''

# PBS queue
queue=''

# Number of nodes
nnodes=1

# Number of cores per node
ncores=1

# Memory per node (GB)
mem=1

# Runtime
runtime=00:30:00

# Parse command line parameters
OPTIONS=`getopt -o c:f:G:hJ:j:m:n:q:R:s:t: -l ncores:,flags:,graph:,'help',nodes:,start:,njobs:,queue:,readjob:,nsamples:,memory:,runtime: -n 'causet_wrp' -- "$@"`

if [ $? -ne 0 ] ; then
  echo "Unrecognized option. Try running with --help flag." >&2
  exit 1
fi

eval set -- "$OPTIONS"

while true ; do
  case "$1" in
    -c|--ncores)
      case "$2" in
        "") shift 2 ;;
        *) ncores=$2 ; shift 2 ;;
      esac ;;
    -f|--flags)
      case "$2" in
        "") shift 2 ;;
        *) flags=$2 ; shift 2 ;;
      esac ;;
    -G|--graph)
      case "$2" in
        "") shift 2 ;;
        *) readgraphid=$2 ; shift 2 ;;
      esac ;;
    -J|--start)
      case "$2" in
        "") shift 2 ;;
        *) jobstart=$2 ; shift 2 ;;
      esac ;;
    -j|--njobs)
      case "$2" in
        "") shift 2 ;;
        *) njobs=$2 ; shift 2 ;;
      esac ;;
    -m|--memory)
      case "$2" in
        "") shift 2 ;;
        *) mem=$2 ; shift 2 ;;
      esac ;;
    -n|--nodes)
      case "$2" in
        "") shift 2 ;;
        *) nnodes=$2 ; shift 2 ;;
      esac ;;
    -q|--queue)
      case "$2" in
        "") shift 2 ;;
        *) queue=$2 ; shift 2 ;;
      esac ;;
    -R|--readjob)
      case "$2" in
        "") shift 2 ;;
        *) readjobid=$2; shift 2 ;;
      esac ;;
    -s|--nsamples)
      case "$2" in
        "") shift 2 ;;
        *) nsamples=$2 ; shift 2 ;;
      esac ;;
    -t|--runtime)
      case "$2" in
        "") shift 2 ;;
        *) runtime=$2 ; shift 2 ;;
      esac ;;
    -h|--help)
      echo "Usage: causet_wrp [OPTION]..."
      echo "Send CausalSet jobs to PBS partitions on MP2 cluster."
      echo ""
      echo "  -c, --ncores     number of cores requested"
      echo "  -f, --flags      flags to pass to CausalSet program"
      echo "  -G, --graph      graph ID specified when reading a graph from another job"
      echo "  -h, --help       display this help and exit"
      echo "  -J, --start      job ID offset, used for naming directories"
      echo "  -j, --njobs      number of jobs to run in parallel on separate nodes"
      echo "  -m, --memory     memory per job"
      echo "  -n, --nodes      number of nodes"
      echo "  -q, --queue      PBS partition"
      echo "  -R, --readjob    job ID specified when reading graph(s) from another job"
      echo "  -s, --nsamples   number of samples to run serially on a single node"
      echo "  -t, --runtime    time limit"
      echo ""
      echo "Report causet_wrp bugs to wcunningham@perimeterinstitute.ca"
      echo "Bitbucket repository home page: <https://bitbucket.org/dk-lab/2015_code_causets>"
      exit 0 ;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 2 ;;
  esac
done

# Check if 'jobstart' is an integer or a string
num='^[0-9]+$' # Regular expression here
istart=1
notnumber=0 # Assume jobstart is a number by default
if ! [[ "$jobstart" =~ $num ]] ; then # Not a number
  njobs=1
  notnumber=1
else
  istart=$jobstart
fi

# Format runtime
runtime=$(echo $runtime | sed "s:\::\\\\\::g")

# Send jobs to PBS via qsub
jobid=$jobstart
for (( i=${istart}; i<${njobs}+${istart}; i++ )) ; do
  if [ ${notnumber} -eq 0 ] ; then
    jobid=$i
  fi
  if [[ ${readjobid} -ne 0 && ${readjobid} -eq ${jobid} ]] ; then
    echo "Invalid option: jobid equals readjobid!"
    exit 3;
  fi
  mkdir -p $SCRATCH_DIR
  mkdir -p $SCRATCH_DIR/causet${jobid}
  sed "s:%flags%:$flags:g;s:%jobID%:$jobid:g;s:%nsamples%:$nsamples:g;s:%queue%:$queue:g;s:%ncores%:$ncores:g;s:%nnodes%:$nnodes:g;s:%readgraphid%:$readgraphid:g;s:%readjobid%:$readjobid:g;s:%mem%:$mem:g;s:%runtime%:$runtime:g" < $CAUSET_HOME_DIR/pbs/batch/causet_pbs | qsub
  #sed "s:%flags%:$flags:g;s:%jobID%:$jobid:g;s:%nsamples%:$nsamples:g;s:%queue%:$queue:g;s:%ncores%:$ncores:g;s:%nnodes%:$nnodes:g;s:%readgraphid%:$readgraphid:g;s:%readjobid%:$readjobid:g;s:%mem%:$mem:g;s:%runtime%:$runtime:g" < $CAUSET_HOME_DIR/pbs/batch/causet_pbs > $CAUSET_HOME_DIR/batch_test$jobid
  sleep 1
done
