#!/bin/bash

# Prevents re-compiling during a long run
#mv Makefile Makefile~

#These will reproduce known results

# Generate causal set for 1+1 de Sitter (no matter)
#./bin/CausalSet --nodes 24586 --degrees 5.53 --dim 1 --seed 18100 --verbose
# Should find eta0 = 1.5707577, gamma = 2

# Generate causal set for 3+1 de Sitter (no matter)
#./bin/CausalSet --nodes 25441 --degrees 5.29 --radius 2.0 --seed 18100 -y --verbose
# Should find eta0 = 1.5296963, gamma = 1.75

# Generate causal set for universe (mix of dark energy and matter)
#./bin/CausalSet --universe --age 0.8458 --alpha 2.01 --delta 10000 --seed 18100 -y --print --verbose &> causet.log &
# Should find N = 10^6, tau given by (12), in-degree given by Fig. (S3), out-degree given by Fig. (3a)

# Read hyperbolic graph data and measure greedy routing
#./bin/CausalSet --dim 1 --manifold h --seed 18100 --graph 321 -y --verbose --success 1
# Should find a success ratio of 1.0 and a single connected component

#These are experimental parameters

# Measure properties of 3+1 de Sitter
#./bin/CausalSet --nodes 20480 --degrees 5.29 --radius 2.0 --seed 84450 -y --verbose --gpu --success 0.001

#Measure properties of Universe
#./bin/CausalSet --universe --age 3.6 --nodes 10240 --delta 1.0 --radius 0.8 --seed 84450 -y --verbose --gpu
./bin/CausalSet --universe --age 0.8458 --nodes 10240 --delta 1000 --seed 84450 -y --verbose --gpu --components --embedding 0.01

#mv Makefile~ Makefile
