#!/bin/bash

set -eu -o pipefail

if [[ -z "$CAUSET_HOME_DIR" ]] ; then
  echo "Using $PWD as your project directory."
  echo "Adding this variable to your .bashrc file."
  echo "export CAUSET_HOME_DIR=$PWD" >> /home/$USER/.bashrc
  source /home/$USER/.bashrc
fi

if [[ -z "$CAUSET_LOCAL_DIR" ]] ; then
  echo "Using $CAUSET_HOME_DIR/local as your local directory."
  echo "Adding this variable to your .bashrc file."
  mkdir -p local
  CAUSET_LOCAL_DIR=$CAUSET_HOME_DIR/local
  echo "export CAUSET_LOCAL_DIR=$CAUSET_LOCAL_DIR" >> /home/$USER/.bashrc
  source /home/$USER/.bashrc
fi

PLATFORM=""
if [[ "$#" -eq 1 ]] ; then
  PLATFORM="_$1"
fi

cd $CAUSET_HOME_DIR/opt/printcolor
make; make install; make clean

cd $CAUSET_HOME_DIR/opt/nintlib
make; make install; make clean

# Remote project locations
FASTMATH_BB="git@bitbucket.org:dk-lab/2015_code_fastmath.git"

if [[ -z "$FAST_LOCAL_DIR" ]] ; then
  export "FAST_LOCAL_DIR=$CAUSET_LOCAL_DIR" >> /home/$USER/.bashrc
  source /home/$USER/.bashrc
fi

if [[ ! -d "$CAUSET_HOME_DIR/opt/fastmath" ]] ; then
  git clone $FASTMATH_BB $CAUSET_HOME_DIR/opt/fastmath
  echo "Run one more time."
  exit 1
fi

if [[ ! -d "$CAUSET_HOME_DIR/opt/fastmath" ]] ; then
  echo "Something went wrong with git..."
  exit 2
fi
cd $CAUSET_HOME_DIR/opt/fastmath
./INSTALL
cd $CAUSET_HOME_DIR

AVX=0
if [[ $(cat /proc/cpuinfo | grep avx2 | wc -l) -ne 0 ]] ; then
  echo "AVX2 support detected."
  AVX=1
  AVX_FLAGS="-mavx2 -march=core-avx2 -mtune=core-avx2 -mpopcnt -DAVX2_ENABLED"
else
  AVX_FLAGS=""
fi

if [[ $(lspci | grep NVIDIA | wc -l) -ne 0 ]] ; then
  echo "NVIDIA graphics card detected."
  echo "Attempting to locate CUDA install path..."

  CUDA_HOME=$(which nvcc | sed "s/\/bin\/nvcc//")
  echo "  Using CUDA path $CUDA_HOME."
  CUDA_SDK_PATH=$CUDA_HOME/samples
  NVCC=$CUDA_HOME/bin/nvcc
  CUDA_INCD="-I $CUDA_SDK_PATH/common/inc -I $CUDA_HOME/include"
  CUDA_LIBS="-L /usr/lib/nvidia-current -L $CUDA_HOME/lib64 -L $CUDA_SDK_PATH/common/lib -lcuda -lcudart"
  NVCC_FLAGS="-O3 -G -g -DBOOST_NOINLINE='__attribute__ ((noinline))' -DCUDA_ENABLED -arch=sm_35 --std=c++11 -DBOOST_NO_FENV_H"
  GPU_TARGET="check-env dirs \$(COBJS) \$(CUDAOBJS) linkgpu bin"

  GLOB_MEM_MIB=$(nvidia-smi -q | grep -A3 "FB Memory Usage" | awk '/Total/ {print $3}')
  GLOB_MEM_BYTES=$(($(echo "scale=8; $GLOB_MEM_MIB * 1.049 / 1000" | bc | awk '{printf("%d\n", $1)}') * 1000000000))
  sed "s:%GLOB_MEM%:$GLOB_MEM_BYTES:g" < $CAUSET_HOME_DIR/inc/Constants.in > $CAUSET_HOME_DIR/inc/Constants.h
  echo "Use 'make gpu' to compile with GPU features enabled."
  echo "NOTE: If your graphics card does not have Compute Capability 3.5, you must edit the -arch flag in the Makefile!"
else
  CUDA_HOME=""
  CUDA_SDK_PATH=""
  NVCC=""
  CUDA_INCD=""
  CUDA_LIBS=""
  NVCC_FLAGS=""
  GPU_TARGET=""
  sed "s:%GLOB_MEM%:0:g" < $CAUSET_HOME_DIR/inc/Constants.in > $CAUSET_HOME_DIR/inc/Constants.h
fi

sed "s:%CUDA_HOME%:$CUDA_HOME:g;s:%CUDA_SDK_PATH%:$CUDA_SDK_PATH:g;s:%NVCC%:$NVCC:g;s:%CUDA_INCD%:$CUDA_INCD:g;s:%CUDA_LIBS%:$CUDA_LIBS:g;s:%NVCC_FLAGS%:$NVCC_FLAGS:g;s:%GPU_TARGET%:$GPU_TARGET:g;s:%AVX%:$AVX:g;s:%AVX_FLAGS%:$AVX_FLAGS:g;s:%PLATFORM%:$PLATFORM:g" < $CAUSET_HOME_DIR/Makefile.in > $CAUSET_HOME_DIR/Makefile

$CAUSET_HOME_DIR/etc/mkdat
cd $CAUSET_HOME_DIR
make clean
