#!/bin/bash

###########################
#(C) Will Cunningham 2014 #
# Krioukov Research Group #
# Northeastern University #
###########################

####################################
# Examples of How to Use CausalSet #
####################################

# 1+1 de Sitter, spherical foliation
#./bin/CausalSet --nodes 24586 --age 1.5707577 --dim 1 --compact --link --print

# 3+1 de Sitter, spherical foliation
#./bin/CausalSet --nodes 65536 --age 1.2 --buffer 0.3 --compact --link --gpu --print

# 3+1 de Sitter, flat foliation
#./bin/CausalSet --nodes 122880 --age 0.848152 --slice 4.9997 --buffer 0.3 --link --gpu --print

# 3+1 Dust, flat foliation
#./bin/CausalSet --nodes 10240 --age 0.848152 --alpha 2 --manifold d --link --gpu --print

# 3+1 FLRW, flat foliation
#./bin/CausalSet --nodes 10240 --energy 0.7 --alpha 3 --manifold f --link --gpu --print

# 1+1 Hyperbolic, reading file 'dat/pos/321.cset.pos.dat'
#./bin/CausalSet --graph 321 --dim 1 --manifold h --relink --print

########################
# The Validation Tests #
########################

# de Sitter Embedding
#./bin/CausalSet --nodes 20480 --age 1.5 --seed 18100 --buffer 0.3 --compact --link --embedding 100

# de Sitter Distances
#./bin/CausalSet --nodes 2048 --age 1.2 --seed 18100 --buffer 0.3 --compact --link --gpu --distances 100

# FLRW Distances
#./bin/CausalSet --nodes 10240 --energy 0.7 --alpha 2 --seed 18100 --manifold f --compact --link --gpu --distances 100


#####################################
# These are experimental parameters #
#####################################

for (( i=0; i<1; i++ )) ; do
./bin/CausalSet --nodes 8192 --age 0.5 --manifold f --alpha 5 --buffer 0.3 --verbose -y --test
done

# Study Dust Manifold
#./bin/CausalSet --nodes 26624 --age 0.2154 --alpha 2.9941 --manifold d --link --gpu

# Greedy Routing
#./bin/CausalSet --nodes 3513 --age 0.761631 --buffer 0.3 --link --verbose -y --test
#energy=0.82
#num=40704
#rad=5.9908
#seed=1444666562
#./bin/CausalSet --nodes $num --age $age --slice $rad --buffer 0.3 --verbose -y --gpu --link --success 200
#./bin/CausalSet --nodes $num --energy $energy --alpha $rad --seed $seed --manifold d --link --gpu --success 100000
#./bin/CausalSet --nodes $num --alpha $rad --age $age --manifold f --verbose -y --link --gpu --success 1000
#./bin/CausalSet --energy 0.975 --alpha 5.9993 --graph 1440786261 --manifold f --link --verbose -y --success 20000000

# Measure de Sitter Action
#./bin/CausalSet --graph 1 --age 0.5 --buffer 0.3 --manifold s --compact --link --quiet-read --components --action smeared --print
#for (( i=0; i<5; i++ )) ; do
#./bin/CausalSet --nodes 1024 --age 0.5 --buffer 0.3 --manifold s --compact --link --gpu
#done
#./bin/CausalSet --nodes 32768 --age 1.2 --seed 18100 --buffer 0.3 --verbose -y --link --gpu --action 5 --core 1

######################################
# These will reproduce known results #
######################################

# Generate causal set for 1+1 de Sitter (no matter)
#./bin/CausalSet --nodes 24586 --age 1.5707577 --dim 1 --seed 18100 --link --print
# Should find k = 5.53, gamma = 2

# Generate causal set for 3+1 de Sitter (no matter)
#./bin/CausalSet --nodes 25441 --age 1.5296963 --seed 18100 --buffer 0.3 --link --print
# Should find k = 5.29, gamma = 1.75

# Generate causal set for universe (mix of dark energy and matter)
#./bin/CausalSet --nodes 1000887 --age 0.8458 --alpha 2.01 --delta 10000 --seed 18100 --manifold f --compact --link --verbose -y --print &> causet.log &
# Should find k = 727, in-degree given by Fig. (S3), out-degree given by Fig. (3a)
# Note this takes ~ 3.5 days to run!!!

# Read hyperbolic graph data and perform greedy routing algorithm
#./bin/CausalSet --graph 321 --dim 1 --manifold h --seed 18100 --verbose -y --success 1
# Should find a success ratio of 1.0 and a single connected component

# Compare to Dima's Fortran Code
# Make sure to manually alter parameters in fortran code and re-compile!
#./bin/CausalSet --graph 22222 --nodes 10240 --age 1.5 --delta 1 --manifold f --compact --link --gpu --components
#./etc/dk_stats_direct.pl 22222
