#!/bin/bash

###########################
#(C) Will Cunningham 2014 #
#         DK Lab          #
# Northeastern University #
###########################

####################################
# Examples of How to Use CausalSet #
####################################

# 1+1 flat Minkowski diamond
#./bin/CausalSet --spacetime 11274 --nodes 1000 --age 0.5 --link --print

# 1+1 de Sitter, spherical foliation
#./bin/CausalSet --spacetime 12834 --nodes 24586 --age 1.5707577 --link --print

# 3+1 de Sitter, spherical foliation
#./bin/CausalSet --spacetime 12836 --nodes 65536 --age 1.2 --buffer 0.3 --link --gpu --print

# 3+1 de Sitter, flat foliation
#./bin/CausalSet --spacetime 10788 --nodes 122880 --age 0.848152 --slice 4.9997 --buffer 0.3 --link --gpu --print

# 3+1 Dust, flat foliation
#./bin/CausalSet --spacetime 10820 --nodes 65536 --age 0.848152 --alpha 5 --link --gpu --print

# 3+1 FLRW, flat foliation
#./bin/CausalSet --spacetime 10884 --nodes 10240 --energy 0.7 --alpha 3 --link --gpu --print

# 1+1 Hyperbolic, reading file 'dat/pos/321.cset.pos.dat'
#./bin/CausalSet --graph 321 --dim 1 --manifold h --relink --print

########################
# The Validation Tests #
########################

# de Sitter Embedding
#./bin/CausalSet --spacetime 12836 --nodes 20480 --age 1.5 --seed 18100 --buffer 0.3 --link --gpu --embedding 1

# de Sitter Distances
#./bin/CausalSet --spacetime 12836 --nodes 2048 --age 1.2 --seed 18100 --buffer 0.3 --link --gpu --distances 100

#####################################
# These are experimental parameters #
#####################################

# Greedy routing experiments:
#  > omega_lambda = {0.73, 0.99}
#  > q = {200000, 250000, 300000}
#  > k = {20000, 40000, 60000}
#  > N_sr = 10000000
#  > N_samples = 10

# Greedy Routing
st=21028
#st=12836
age=0.5
#energy=0.81
num=832255
#seed=1458742213
./bin/CausalSet_krioukov_gpu --spacetime $st --nodes $num --age $age --verbose --link --gpu --core 1

# Measure de Sitter Action
#./bin/CausalSet --spacetime 12834 --nodes 32768 --age 1.2 --seed 18100 --buffer 0.3 --link --gpu --action local --core 1

######################################
# These will reproduce known results #
######################################

# Generate causal set for 1+1 de Sitter (no matter)
#./bin/CausalSet --spacetime 12834 --nodes 24586 --age 1.5707577 --seed 18100 --link --print
# Should find k = 5.53, gamma = 2

# Generate causal set for 3+1 de Sitter (no matter)
#./bin/CausalSet --spacetime 12836 --nodes 25441 --age 1.5296963 --seed 18100 --buffer 0.3 --link --print
# Should find k = 5.29, gamma = 1.75

# Generate causal set for FLRW universe (mix of dark energy and matter)
#./bin/CausalSet --spacetime 12932 --nodes 1000887 --age 0.8458 --alpha 2.01 --delta 10000 --seed 18100 --link --gpu --verbose -y --print &> causet.log &
# Should find k = 727, in-degree given by Fig. (S3), out-degree given by Fig. (3a)
# Note this takes ~ 3.5 days to run without the GPU!!!

# Read hyperbolic graph data and perform greedy routing algorithm
#./bin/CausalSet --spacetime 11010 --graph 321 --seed 18100 --verbose -y --success 1
# Should find a success ratio of 1.0 and a single connected component

# Compare to Dima's Fortran Code
# Make sure to manually alter parameters in fortran code and re-compile!
#./bin/CausalSet --spacetime 12932 --graph 22222 --nodes 10240 --age 1.5 --delta 1 --link --gpu --components
#./etc/dk_stats_direct.pl 22222
