#!/bin/bash

###########################
#(C) Will Cunningham 2014 #
#         DK Lab          #
# Northeastern University #
###########################

set -eu -o pipefail

$CAUSET_HOME/etc/testbed

# NOTE: The variable used for spacetime may change, and should be cross-referenced with doc/VERSION.
# The current version is indicated in the file inc/config.h

#####################################
# These are experimental parameters #
#####################################

platform=$PLATFORM
binary="./CausalSet_${platform}"
makenew=true

type="rgg"
st="120002011" # 2D Minkowski Slab_T2 (convex)
#st="A0200011" # 2D Minkowski Diamond
spacetime="--type $type --spacetime $st"
#spacetime="--type rgg --stdim 2 --manifold Minkowski --region Slab_T2 --curvature Flat --symmetry Temporal"

nodes=4096
age=0.6
alpha=1.0
radius=0.6
constraints="--nodes $nodes --age $age --alpha $alpha --radius $radius"

if [[ "$makenew" == "true" ]] ; then
  link="--link --gpu"
  measure="--extrinsic"
  xtra="--verbose -y --binomial --seed 18101"
else
  basedir=$CAUSET_HOME
  graphs=($(awk '{print $1}' $basedir/etc/data_keys.cset.key))
  graph=${graphs[${#graphs[@]}-1]}

  link="--link --core 1"
  measure="--antichain"
  xtra="--verbose -y --graph ${graph} --nopos"
fi

(cd $TBDIR/causets && $binary $spacetime $constraints $link $measure $xtra)

####################################
# Examples of How to Use CausalSet #
####################################

# 1+1 flat Minkowski diamond
#./bin/CausalSet --spacetime 11274 --nodes 1000 --age 0.5 --link --print

# 1+1 de Sitter, spherical foliation
#./bin/CausalSet --spacetime 12834 --nodes 24586 --age 1.5707577 --link --print

# 3+1 de Sitter, spherical foliation
#./bin/CausalSet --spacetime 12836 --nodes 65536 --age 1.2 --buffer 0.3 --link --gpu --print

# 3+1 de Sitter, flat foliation
#./bin/CausalSet --spacetime 10788 --nodes 122880 --age 0.848152 --slice 4.9997 --buffer 0.3 --link --gpu --print

# 3+1 Dust, flat foliation
#./bin/CausalSet --spacetime 10820 --nodes 65536 --age 0.848152 --alpha 5 --link --gpu --print

# 3+1 FLRW, flat foliation
#./bin/CausalSet --spacetime 10884 --nodes 10240 --energy 0.7 --alpha 3 --link --gpu --print

# 1+1 Hyperbolic, reading file 'dat/pos/321.cset.pos.dat'
#./bin/CausalSet --graph 321 --dim 1 --manifold h --relink --print

########################
# The Validation Tests #
########################

# de Sitter Embedding
#./bin/CausalSet --spacetime 12836 --nodes 20480 --age 1.5 --seed 18100 --buffer 0.3 --link --gpu --embedding 1

# de Sitter Distances
#./bin/CausalSet --spacetime 12836 --nodes 2048 --age 1.2 --seed 18100 --buffer 0.3 --link --gpu --distances 100

######################################
# These will reproduce known results #
######################################

# Note: these spacetime values are for Version 0

# Generate causal set for 1+1 de Sitter (no matter)
#./bin/CausalSet --spacetime 12834 --nodes 24586 --age 1.5707577 --seed 18100 --link --print
# Should find k = 5.53, gamma = 2

# Generate causal set for 3+1 de Sitter (no matter)
#./bin/CausalSet --spacetime 12836 --nodes 25441 --age 1.5296963 --seed 18100 --buffer 0.3 --link --print
# Should find k = 5.29, gamma = 1.75

# Generate causal set for FLRW universe (mix of dark energy and matter)
#./bin/CausalSet --spacetime 12932 --nodes 1000887 --age 0.8458 --alpha 2.01 --delta 10000 --seed 18100 --link --gpu --verbose -y --print &> causet.log &
# Should find k = 727, in-degree given by Fig. (S3), out-degree given by Fig. (3a)
# Note this takes ~ 3.5 days to run without the GPU!!!

# Read hyperbolic graph data and perform greedy routing algorithm
#./bin/CausalSet --spacetime 11010 --graph 321 --seed 18100 --verbose -y --success 1
# Should find a success ratio of 1.0 and a single connected component

# Compare to Dima's Fortran Code
# Make sure to manually alter parameters in fortran code and re-compile!
#./bin/CausalSet --spacetime 12932 --graph 22222 --nodes 10240 --age 1.5 --delta 1 --link --gpu --components
#./etc/dk_stats_direct.pl 22222
