#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Creates a parameter file which lsf/tests/action can read (for many runs)

set -eu -o pipefail

if [[ "$#" -lt 3 ]] ; then
  echo "Arguments are [min] [max] [num]"
  exit 1
fi

min=$1
max=$2
num=$3

basedir=$CAUSET_HOME_DIR/etc/action
while IFS=' ' read -r -a avals ; do
  for i in $(seq ${#avals[@]}) ; do
    echo ${avals[${i}-1]} >> $CAUSET_HOME_DIR/causet.par
  done
done <<< $($basedir/action_params $min $max $num)
