#!/usr/bin/env python

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

import glob
import os.path
from shutil import copyfile
import sys

if len(sys.argv) < 5:
	sys.stdout.write('Arguments are [jobstart] [jobend] [number of nodes] [number of mpi threads]\n')
	sys.exit(1)

jobstart = int(sys.argv[1])
jobend = int(sys.argv[2])
N = int(sys.argv[3])
mpi = int(sys.argv[4])

if N < 0 or mpi <= 0:
	sys.stdout.write('Invalid arguments.\n')
	sys.exit(2)

basedir = ''
#for i in range(jobstart, jobend):
#	copyfile(basedir + '/causet' + str(i) + '/dat/act/cards*', basedir + '/causet' + str(jobend) + '/dat/act')

cards = []
for i in range(N):
	cards.append(0)

for i in range(2 * mpi - 1):
	for j in range(i + 1, 2 * mpi):
		filename = 'dat/act/cards_' + str(i) + str(j) + '.cset.act.dat'
		if not os.path.exists(basedir + filename):
			sys.stdout.write('Missing file: %s\n' % (basedir + filename))
			sys.exit(3)

		f = open(filename)
		lines = f.readlines()
		idx = 0
		for line in lines:
			cards[idx] += int(line)
			idx += 1
		f.close()
cards[0] = N

h = open(basedir + 'dat/act/cardinalities.cset.act.dat')
for i in range(N):
	h.write(str(cards[i]) + '\n')
h.close()

sys.stdout.write('Completed ACT.\n')
