#!/bin/bash

###########################
#(C) Will Cunningham 2018 #
#         DK Lab          #
# Northeastern University #
###########################

set -eu -o pipefail

basedir=$SCRATCH_DIR

if [[ "$#" -ge 1 ]] ; then
  basedir=$basedir/causet$1
fi

outfile=output.dat
if [[ "$#" -eq 2 ]] ; then
  outfile=$2
fi

rm -f $CAUSET_HOME/$outfile
for file in $basedir/dat/act/*.cset.act.dat ; do
  tr '\n' ' ' < $file | awk 'NR==1' >> $CAUSET_HOME/$outfile
done
