#!/usr/bin/env python

###########################
#(C) Will Cunningham 2015 #
# Krioukov Research Group #
# Northeastern University #
###########################

# Calculates the average and standard error of the action over several lk
# Note this script should only be used for the smeared action

import glob
import math
import numpy as np
import sys

stdim = 2

if not (stdim == 2 or stdim == 4):
	sys.stdout.write('Invalid parameter: [stdim]');
	sys.exit(1)

# Range of job numbers (inclusive)
jobStart = 506
jobEnd = 519
njobs = jobEnd - jobStart + 1

# Range of lk to use (inclusive)
lkmin = 2
lkmax = 10
lkstep = 1
nlk = (lkmax - lkmin + 1) / lkstep

basedir = '/scratch/cunningham/'
action = np.zeros((nlk, njobs))
err = np.zeros((nlk, njobs))

for lk in range(lkmin, lkmax + lkstep, lkstep):	
	epsilon = math.pow(lk, -stdim)
	eps1 = epsilon / (1.0 - epsilon)

	for job in range(jobStart, jobEnd + 1):
		files = glob.glob(basedir + 'causet' + str(job) + '/dat/act/*.cset.act.dat')
		a = np.zeros(len(files))
		c = []
		n = 0
		a_idx = 0

		for file in files:
			f = open(file)
			lines = f.readlines()
			c = []
			c_idx = 0

			for line in lines:
				c.append(int(line))
				c_idx += 1

			f.close()
#			n = c_idx + 1

			for i in range(0, c[0] - 2):
				ni = float(c[i+1])
				if stdim == 2:
					a[a_idx] += ni * math.pow(1.0 - epsilon, i) * (1.0 - 2.0 * eps1 * i + 0.5 * eps1 * eps1 * i * (i - 1.0))
				elif stdim == 4:
					a[a_idx] += ni * math.pow(1.0 - epsilon, i) * (1.0 - 9.0 * eps1 * i + 8.0 * eps1 * eps1 * i * (i - 1.0) - (4.0 / 3.0) * eps1 * eps1 * eps1 * i * (i - 1.0) * (i - 2.0))

			if stdim == 2:
				a[a_idx] = 2.0 * epsilon * (c[0] - 2.0 * epsilon * a[a_idx])
			elif stdim == 4:
				a[a_idx] = (4.0 / math.sqrt(6.0)) * (math.sqrt(epsilon) * c[0] - math.pow(epsilon, 1.5) * a[a_idx])

			a_idx += 1

		if c[0] == 0:
			sys.stdout.write('Error: n = 0!.\n')
			sys.exit(1)

		action[int((lk-lkmin)/lkstep)][int(job-jobStart)] = np.mean(a)
		err[int((lk-lkmin)/lkstep)][int(job-jobStart)] = np.std(a) / math.sqrt(len(files))

basedir = '/home/cunningham.wi/projects/causets/dat/ref/'

if stdim == 2:
	filename = 'd2_'
elif stdim == 4:
	filename = 'd4_'
filename += 'smeared'

f = open(basedir + 'action_' + filename + '.cset.act.ref', 'w')
g = open(basedir + 'stderr_' + filename + '.cset.act.ref', 'w')
for i in range(nlk):
	for j in range(njobs):
		f.write(str(action[i][j]) + ' ')
		g.write(str(err[i][j]) + ' ')
	f.write('\n')
	g.write('\n')
f.close()
g.close()

sys.stdout.write('Completed ACT2.\n')
