#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Use this to broadcast a local file to many data sets

set -eu -o pipefail

start=2382
end=2393

basedir=/gss_gpfs_scratch/cunningham
#basedir=/krioukov/will

sourcefile=$CAUSET_HOME_DIR/etc/stretch
dest=etc

for i in $(seq $start $end) ; do
  dir=$basedir/causet${i}
  if [[ -e $dir ]] ; then
    cp $sourcefile $dir/$dest
  fi
done
