#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Use this to broadcast a local file to many data sets

set -eu -o pipefail

start=1499
end=1506

basedir=/gss_gpfs_scratch/cunningham

sourcefile=$CAUSET_HOME_DIR/etc/action/action_single
dest=etc

for i in $(seq $start $end) ; do
  dir=$basedir/causet${i}
  cp $sourcefile $dir/$dest
done
