#!/usr/bin/env python

###########################
#(C) Will Cunningham 2014 #
#         DK Lab          #
# Northeastern University #
###########################

# Concatenates clustering-by-degree distribution files

import glob
import sys

if (len(sys.argv) < 2):
	sys.stdout.write('Must specify target number of nodes.\n')
	sys.exit(1)

N = int(sys.argv[1])

basedir = ''
files = glob.glob(basedir + 'dat/cdk/*.cset.cdk.dat')
c = []

for i in range(0,N):
	c.append(0)

for file in cdk_files:
	h = open(file)
	lines = h.readlines();
	for line in lines:
		token1,token2 = (float(x) for x in line.split())
		c[int(token1)] += token2
	h.close()

h = open(basedir + 'dat/ref/cdk_dist.cset.cls.ref','w')
for i in range(0,N):
	if (c[i]):
		h.write(str(i) + ' ' + str(c[i]) + '\n')
h.close()

sys.stdout.write('Completed CDK.\n')
