#!/usr/bin/python

###########################
#(C) Will Cunningham 2014 #
# Krioukov Research Group #
# Northeastern University #
###########################

# Computes the distribution and expectation value of the average clustering

import glob
import sys

#basedir = '/scratch/cunningham/causets/'
basedir = ''
files = glob.glob(basedir + 'dat/*.cset.out')

N = len(files)
c = []
avg = 0

for i in range(0,N):
	c.append(0)

idx = 0
for file in files:
	f = open(file)
	lines = f.readlines()

	for line in lines:
		tokens = line.split()
		if len(tokens) == 0:
			continue

		if tokens[0] == 'Average' and tokens[1] == 'Clustering':
			c[idx] = float(tokens[2])
			avg += c[idx]
			idx += 1
			continue
		
	f.close()

avg /= N
sys.stdout.write('Average Clustering: %f\n' % avg)

f = open(basedir + 'dat/ref/average_c.cset.cls.ref','w')
for i in range(0,N):
	f.write(str(c[i]) + '\n')
f.close()

sys.stdout.write('Completed CLS.\n')
