#!/usr/bin/python

###########################
#(C) Will Cunningham 2014 #
# Krioukov Research Group #
# Northeastern University #
###########################

# Concatenates confusion matrix data for embedding validation test

import glob
import sys

#basedir = '/scratch/cunningham/causets/'
basedir = ''
cfiles = glob.glob(basedir + 'dat/emb/*.cset.emb.dat')
fpfiles = glob.glob(basedir + 'dat/emb/fp/*.cset.emb_fp.dat')

confusion = []
for i in range(0,4):
	confusion.append(0)

fp_eta = []
fp_theta = []

for file in cfiles:
	f = open(file)
	lines = f.readlines()

	for i in range(0,4):
		confusion[i] += float(lines[i].split()[2]) / len(cfiles)

	f.close()

for file in fpfiles:
	f = open(file)
	lines = f.readlines()

	for line in lines:
		token1,token2 = (float(x) for x in line.split())
		fp_eta.append(token1);
		fp_theta.append(token2);

	f.close()

f = open(basedir + 'dat/ref/confusion.cset.emb.ref','w')
for i in range(0,4):
	f.write(str(confusion[i]) + '\n')
f.close()

f = open(basedir + 'dat/ref/fp.cset.emb.ref','w')
for i in range(0,len(fp_eta)):
	f.write(str(fp_eta[i]) + ' ' + str(fp_theta[i]) + '\n')
f.close()

sys.stdout.write('Completed EMB.\n')
