#!/usr/bin/env python

###########################
#(C) Will Cunningham 2014 #
# Krioukov Research Group #
# Northeastern University #
###########################

# Concatenates in-degree and out-degree distribution files

import glob
import sys

if (len(sys.argv) == 1):
	sys.stdout.write('Must specify target number of nodes.\n')
	sys.exit(1)
elif (len(sys.argv) > 2):
	sys.stdout.write('Too many parameters specified.\n')
	sys.exit(2)

N = int(sys.argv[1])

if (N < 0):
	sys.stdout.write('Invalid argument.\n')
	sys.exit(3)

#basedir = '/scratch/cunningham/causets/'
basedir = ''
idd_files = glob.glob(basedir + 'dat/idd/*.cset.idd.dat')
odd_files = glob.glob(basedir + 'dat/odd/*.cset.odd.dat')

k_in = []
k_out = []

for i in range(0,N):
	k_in.append(0)
for i in range(0,N):
	k_out.append(0)

for file in idd_files:
	h = open(file)
	lines = h.readlines()
	for line in lines:
		token1,token2 = (int(x) for x in line.split())
		k_in[token1] += token2
	h.close()
for file in odd_files:
	h = open(file)
	lines = h.readlines()
	for line in lines:
		token1,token2 = (int(x) for x in line.split())
		k_out[token1] += token2
	h.close()

h = open(basedir + 'dat/ref/in_degrees.cset.dst.ref','w')
for i in range(0,N):
	if (k_in[i] > 0):
		h.write(str(i) + ' ' + str(k_in[i]) + '\n')
h.close()

h = open(basedir + 'dat/ref/out_degrees.cset.dst.ref','w')
for i in range(0,N):
	if (k_out[i] > 0):
		h.write(str(i) + ' ' + str(k_out[i]) + '\n')
h.close()

sys.stdout.write('Completed DST.\n')
