#!/usr/bin/env python

###########################
#(C) Will Cunningham 2014 #
# Krioukov Research Group #
# Northeastern University #
###########################

# Computes the distribution and expectation value of the average degrees

import glob
import sys

#basedir = '/scratch/cunningham/causets/'
basedir = ''
files = glob.glob(basedir + 'dat/*.cset.out')

N = len(files)
k = []
eps = []
avg = 0
avg_eps = 0

for i in range(0,N):
	k.append(0)
	eps.append(0)

idx = 0
for file in files:
	f = open(file)
	lines = f.readlines()

	for line in lines:
		tokens = line.split()
		if len(tokens) == 0:
			continue

		if tokens[0] == 'Resulting' and tokens[1] == 'Average' and tokens[2] == 'Degrees':
			k[idx] = float(tokens[4])

		if tokens[0] == 'Resulting' and tokens[1] == 'Error' and tokens[2] == 'in' and tokens[3] == '<k>':
			eps[idx] = float(tokens[4])
	
	avg += k[idx]
	avg_eps += eps[idx]
	idx += 1

	f.close()

avg /= N
avg_eps /= N
sys.stdout.write('Average Degrees: %f\n' % avg)
sys.stdout.write('Average Error: %f\n' % avg_eps)

f = open(basedir + 'dat/ref/average_k.cset.deg.ref','w')
for i in range(0,N):
	f.write(str(k[i]) + '\n')
f.close()

f = open(basedir + 'dat/ref/error_k.cset.deg.ref','w')
for i in range(0,N):
	f.write(str(eps[i]) + '\n')
f.close()

sys.stdout.write('Completed DEG.\n')
