#!/bin/bash

###########################
#(C) Will Cunningham 2015 #
#         DK Lab          #
# Northeastern University #
###########################

# Converts a dot file to an edge list

if [[ "$#" -ne 2 ]] ; then
  echo "Must specify an input and output filename."
  exit 1
fi

outfile=$2

while IFS='' read -r line || [[ -n "$line" ]] ; do
  for word in $line ; do
    if [[ $word == *"->"* ]] ; then
      ( IFS='->;' ; set -- $word ; echo "${1} ${3}" >> $outfile )
    fi
  done
done < "$1"
