#!/usr/bin/env python

import math
import numpy as np
import sys

k = 20
tau0 = 4.6416
alpha = 15.5
kappa = 6.82491865e+01

omega = math.pow(math.tanh(1.5*tau0), 2)
q = k / kappa
n0 = math.pi * q * math.pow(alpha * tau0, 3)

n1 = 256 * int(math.floor(n0 / 256))
alpha1 = math.pow(n1 / (math.pi * q), 1.0 / 3.0) / tau0

sys.stdout.write('omega: %e\n' % omega)
sys.stdout.write('q:     %e\n' % q)
sys.stdout.write('N:     %d\n' % n1)
sys.stdout.write('alpha: %f\n' % alpha1)
