#!/usr/bin/env python

###########################
#(C) Will Cunningham 2014 #
#         DK Lab          #
# Northeastern University #
###########################

# Concatenates in-degree and out-degree field files

import glob
import sys

#basedir = '/scratch/cunningham/causets/'
basedir = ''
idf_files = glob.glob(basedir + 'dat/idf/*.cset.idf.dat')
odf_files = glob.glob(basedir + 'dat/odf/*.cset.odf.dat')

k_in_field = []
k_out_field = []

in_avg = 0.0
out_avg = 0.0;

for file in idf_files:
	h = open(file)
	lines = h.readlines()
	for line in lines:
		k_in_field.append(int(line))
		in_avg += float(line)
	h.close()

if len(k_in_field) == 0:
	sys.stdout.write('No In-Degree Field Data Found!\n')
else:
	in_avg /= len(k_in_field)
	sys.stdout.write('Average In-Degree Field Value:  %f\n' % in_avg)

for file in odf_files:
	h = open(file)
	lines = h.readlines()
	for line in lines:
		k_out_field.append(int(line))
		out_avg += float(line)
	h.close()

if len(k_out_field) == 0:
	sys.stdout.write('No Out-Degree Field Data Found!\n')
else:
	out_avg /= len(k_out_field)
	sys.stdout.write('Average Out-Degree Field Value: %f\n' % out_avg)

if len(k_in_field) != 0:
	h = open(basedir + 'dat/ref/in_field.cset.deg.ref','w')
	for i in range(0,len(k_in_field)):
		h.write(str(k_in_field[i]) + '\n')
	h.close()

if len(k_out_field) != 0:
	h = open(basedir + 'dat/ref/out_field.cset.deg.ref','w')
	for i in range(0,len(k_out_field)):
		h.write(str(k_out_field[i]) + '\n')
	h.close()

sys.stdout.write('Completed FLD.\n')
