#!/usr/bin/env python

###########################
#(C) Will Cunningham 2017 #
#         DK Lab          #
# Northeastern University #
###########################

# Average number of geodesically disconnected pairs

import glob
import sys

basedir = ''
files = glob.glob(basedir + 'CausalSet_*.log')

N = len(files)
g = []
avg = 0.0
time = 0.0

for i in range(0, N):
	g.append(0)

idx = 0
for file in files:
	f = open(file)
	lines = f.readlines()

	for line in lines:
		tokens = line.split()
		if len(tokens) <= 1:
			continue

		if time == 0.0 and tokens[1] == 'Max.' and tokens[2] == 'Rescaled' and tokens[3] == 'Time:':
			time = float(tokens[4])

		if tokens[1] == 'Fraction' and tokens[2] == 'of' and tokens[3] == 'Pairs:':
			g[idx] = float(tokens[4])
			break

	avg += g[idx]
	idx += 1
	f.close()

if N > 0:
	avg /= N

#sys.stdout.write('Rescaled Time: %f\n' % time)
#sys.stdout.write('Fraction of Disconnected Pairs: %f\n' % avg)
#sys.stdout.write('Completed FGD.\n')

print time, avg
