#!/usr/bin/python

###########################
#(C) Will Cunningham 2014 #
# Krioukov Research Group #
# Northeastern University #
###########################

# Computes the distribution and expectation value of the minimum tau

import glob
import sys

basedir = ''
files = glob.glob(basedir + 'dat/*.cset.out')

N = len(files)
t = []
avg = 0

for i in range(0,N):
	t.append(0)

idx = 0
for file in files:
	f = open(file)
	lines = f.readlines()

	for line in lines:
		tokens = line.split()
		if len(tokens) == 0:
			continue

		if tokens[0] == 'Minimum' and tokens[1] == 'Rescaled' and tokens[2] == 'Time':
			t[idx] = float(tokens[3])

	avg += t[idx]
	idx += 1

	f.close()

avg /= N
sys.stdout.write('Average Minimum Time: %f\n' % avg)

f = open(basedir + 'dat/ref/min_tau.cset.pos.ref','w')
for i in range(0,N):
	f.write(str(t[i]) + '\n')
f.close()

sys.stdout.write('Completed MIN.\n')
