#!/bin/bash

###########################
#(C) Will Cunningham 2015 #
#         DK Lab          #
# Northeastern University #
###########################

# This script is used to create the directory structure used
# by the CausalSet program to store data files

set -eu -o pipefail

basedir='.'

if [ "$#" -eq 1 ]; then
  basedir=$1
fi

mkdir -p $basedir/etc
mkdir -p $basedir/data
mkdir -p $basedir/data/action
mkdir -p $basedir/data/boundary_chains
mkdir -p $basedir/data/clustering_by_degree
mkdir -p $basedir/data/clustering
mkdir -p $basedir/data/degree_distribution
mkdir -p $basedir/data/hasse
mkdir -p $basedir/data/edges
mkdir -p $basedir/data/foliation_alexandroff_set
mkdir -p $basedir/data/foliation_timelike
mkdir -p $basedir/data/foliation_spacelike
mkdir -p $basedir/data/hubs
mkdir -p $basedir/data/in_degree_distribution
mkdir -p $basedir/data/layers
mkdir -p $basedir/data/layer_degrees
mkdir -p $basedir/data/longest_chains
mkdir -p $basedir/data/out_degree_distribution
mkdir -p $basedir/data/positions
mkdir -p $basedir/data/spacetime_mutual_information
