#!/bin/bash

###########################
#(C) Will Cunningham 2015 #
# Krioukov Research Group #
# Northeastern University #
###########################

# This script is used to create the directory structure used
# by the CausalSet program to store data files

basedir='.'

if [ "$#" -eq 1 ]; then
  basedir=$1
fi

mkdir -p $basedir/dat
mkdir -p $basedir/dat/act
mkdir -p $basedir/dat/cdk
mkdir -p $basedir/dat/cls
mkdir -p $basedir/dat/dst
mkdir -p $basedir/dat/edg
mkdir -p $basedir/dat/emb
mkdir -p $basedir/dat/emb/fp
mkdir -p $basedir/dat/emb/fn
mkdir -p $basedir/dat/idd
mkdir -p $basedir/dat/idf
mkdir -p $basedir/dat/odd
mkdir -p $basedir/dat/odf
mkdir -p $basedir/dat/pos
mkdir -p $basedir/dat/ref
