#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# This script is used to make a table of k(t) for 
# spacetimes where there exists no theoretical expression

# Spacetime ID
id=11300

# Version
ver=0

# Other relevant parameters
n=20480		# Number of nodes

# Range of times
tmin=0.01
tmax=2.00
tstep=0.01

for i in $(seq ${tmin} ${tstep} ${tmax}) ; do
  echo "$i $(./bin/CausalSet --spacetime $id --nodes $n --age $i --link --gpu --core 1 | awk '/rad:/ {print $2}')" >> /tmp/adeg.tmp
done

cp /tmp/adeg.tmp .
#etc/degtable $id $ver
#mv /tmp/adeg.tmp etc/tables/adeg_${id}_${ver}.tmp
