#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# This script is used to make a table of k(t) for 
# spacetimes where there exists no theoretical expression

# Spacetime ID
id=11396

# Version
ver=0

# Other relevant parameters
n=10240		# Number of nodes

# Range of times
tmin=0.66
tmax=1.5
tstep=0.01

for i in $(seq ${tmin} ${tstep} ${tmax}) ; do
  echo "$i $(./bin/CausalSet --spacetime $id --nodes $n --age $i --link --gpu | awk '/rad:/ {print $2}')" >> /tmp/adeg.tmp
done

etc/degtable $id $ver
mv /tmp/adeg.tmp etc/tables/adeg_${id}_${ver}.tmp
