#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# This script is used to make a table of k(t) for 
# spacetimes where there exists no theoretical expression

set -eu -o pipefail

# Spacetime ID
id=49922

# Version
ver="1_1"

# Other relevant parameters
n=20480		# Number of nodes
platform=par-gpu-2

# Range of times
tmin=0.01
tmax=4.75
tstep=0.01

for i in $(seq ${tmin} ${tstep} ${tmax}) ; do
  echo "$i $($CAUSET_HOME/bin/CausalSet_${platform} --spacetime $id --nodes $n --age $i --slice 5.0 --link --gpu --core 1 | awk '/rad:/ {print $2}')" >> /tmp/adeg.tmp
done

cp /tmp/adeg.tmp .
etc/degtable $id $ver
mv /tmp/adeg.tmp $CAUSET_HOME/etc/tables/adeg_${id}_${ver}.tmp
