#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

#set -eu -o pipefail

# This script is used to generate a new doc/VERSION block when spacetime IDs are updated

if [[ "$#" -lt 1 ]] ; then
  echo "Arguments are [new version]"
  exit 1
fi

version=$1
outfile=$CAUSET_HOME/VERSION

stdims=(2 3 4 5)
manifolds=(Minkowski De_Sitter Anti_de_Sitter Dust FLRW Hyperbolic Polycone)
regions=(Slab Slab_T1 Slab_T2 Slab_TS Slab_S1 Slab_S2 Slab_N1 Slab_N2 Slab_N3 Half_Diamond Diamond Saucer_T Saucer_S Triangle_T Triangle_S Triangle_N Cube)
curvatures=(Flat Positive Negative)
symmetries=(None Temporal)

nodes=1
tcut=0.5
scut=0.5

platform=_$PLATFORM
binary=$CAUSET_HOME/bin/CausalSet$platform

echo -e "\nVERSION ${version}.x" >> $outfile
echo -e "===========\n" >> $outfile
echo -e "STDIM\tMANIFOLD\tREGION\t\tCURVATURE\tSYMMETRY\tID" >> $outfile
echo "================================================================================" >> $outfile

for stdim in ${stdims[@]} ; do
  sdim=$((stdim-1))
  for manifold in ${manifolds[@]} ; do
    for region in ${regions[@]} ; do
      for curvature in ${curvatures[@]} ; do
        for symmetry in ${symmetries[@]} ; do
          id=$($binary --type rgg --binomial --stdim $stdim --manifold $manifold --region $region --curvature $curvature --symmetry $symmetry --nodes $nodes --age $tcut --radius $scut --alpha $scut --test 2>&- | awk '/Spacetime ID:/ {print $4}')
          if [[ "$id" != "" ]] ; then
            #printf "%-8s%-16s%-16s%-16s%-16s%-8s\n" "$sdim+1" $manifold $region $curvature $symmetry $id | awk '{print toupper($0)}' >> $outfile
            printf "%-8s%-16s%-16s%-16s%-16s%-8s\n" $stdim $manifold $region $curvature $symmetry $id | awk '{print $0}' >> $outfile
          fi
        done
      done
    done
  done
done
