#!/usr/bin/env python

# Computes the vector product histogram from the raw data

import glob
import numpy as np
import sys

if len(sys.argv) < 4:
	sys.stdout.write('Arguments are [scale] [spacetime] [version] [optional file suffix].\n')
	sys.exit(1)

scale = sys.argv[1]
spacetime = sys.argv[2]
version = sys.argv[3].replace(".", "_")

if len(sys.argv) == 5:
	suffix = '_' + sys.argv[4]
else:
	suffix = ''

basedir = ''
files = glob.glob(basedir + 'dat/vpd/*.cset.vpd.dat')

v = []
for file in files:
	f = open(file, 'r')
	lines = f.readlines()
	for line in lines:
		v.append(float(line))
	f.close()

y,x = np.histogram(v, bins = 100)

outfile = basedir + 'dat/ref/vecprod_hist_scale-' + scale + '_' + spacetime + '_' + version + suffix + '.cset.vpd.ref'
h = open(outfile, 'w')
for i in range(0,len(x)):
	h.write(str(x[i]) + ' ' + str(y[i]) + '\n')
h.close()

sys.stdout.write('COMPLETED VPD.\n')
