#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Action Experiments

# Use 'setnextjob' command
# Set spacetime details
# Set age
# Specify details of .par file
# Choose 'readstart' and 'samples'
# Choose 'queue' and 'mpi'

set -eu -o pipefail

if [[ "$#" -lt 1 ]] ; then
  echo "Arguments are [parfile]"
  exit 1
fi

type="rgg"
st="A0200081"

age=1.0
radius=0.5
makeparfile=false

nmin=1024
nmax=16384
nnum=5

source $HOME/.queues
jobstart=$NEXT_JOB
readstart=0
samples=10
queue="qwork4"
mpi=1
ncores=12
memory=31 #gigabytes
runtime=24:00:00

makeparfile=false
if [[ "$makeparfile" == "true" ]] ; then
  rm -f $CAUSET_HOME_DIR/causet.par
  $CAUSET_HOME_DIR/etc/action/action_test $nmin $nmax $nnum
  exit 2
fi

parfile=$1
readarray -t vars < $parfile

for i in $(seq ${#vars[@]}) ; do
  job=$(($i+$jobstart-1))
  var=(${vars[${i}-1]})
  if [[ ${var:0:1} == "#" ]] ; then
    continue
  fi

  nodes=$var

  if [[ "$readstart" -ne 0 ]] ; then
    readjob=$(($i+$readstart-1))
    nodes=0
    samples=1

    echo "Attempting to read job $readjob."
    basedir=$SCRATCH_DIR
    if [[ ! -d $basedir/causet${readjob} ]] ; then
      echo "Job ${readjob} could not be found."
      continue
    fi
  else
    readjob=0
  fi

  $CAUSET_HOME_DIR/pbs/wrapper/causet_wrp --queue $queue --ncores $ncores --memory $memory --runtime $runtime --start $job --nsamples $samples --flags "--type $type --spacetime $st --nodes $nodes --binomial --age $age --radius $radius --alpha 1.0 --link --core 1 --action smeared --verbose -y --print --print-edges"
done

setnextjob $(($job+1))
