#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Action Experiments

source /home/$USER/.queues

spacetime=77834
nmin=1024
nmax=65536
nnum=19
age=1.00

jobstart=$NEXT_JOB
readstart=0
samples=10
queue="krioukov_gpu"
exclude="compute-4-017"

host=$(bqueues -l $queue | awk '/HOSTS:/ {print $2}' | sed 's#/*$##')
ncores=$(bhosts $host | awk 'NR==2 {print $4}')

rm -f causet.par
./etc/action/action_test $nmin $nmax $nnum
readarray -t vars < causet.par
rm causet.par

for i in $(seq ${#vars[@]}) ; do
  nodes=${vars[${i}-1]}
  job=$(($i+$jobstart-1))

  if [[ "$readstart" -ne 0 ]] ; then
    readjob=$(($i+$readstart-1))
    nodes=0
  else
    readjob=0
  fi

  ./lsf/wrapper/causet_bat --start $job --readjob $readjob --ncores $ncores --flags '--spacetime '"$spacetime"' --nodes '"$nodes"' --age '"$age"' --link --core 1 --verbose -y --action smeared --print' --queue $queue --nsamples $samples --exclude $exclude
done

setnextjob $(($job+1))
