#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Action Experiments

source /home/$USER/.causet

spacetime=21028
nmin=1024
nmax=262144
nnum=25
age=1.00
jobstart=$NEXT_JOB
readstart=0
samples=10
queue="krioukov_gpu"
exclude="compute-4-017"

#rm -f causet.par
#./etc/action/action_test $nmin $nmax $nnum
readarray -t vars < causet.par
#rm causet.par

for i in $(seq ${#vars[@]}) ; do
  nodes=${vars[${i}-1]}
  job=$(($i+$jobstart-1))

  if [[ "$readstart" -ne 0 ]] ; then
    readjob=$(($i+$readstart-1))
    nodes=0
  else
    readjob=0
  fi

  if [[ "$queue" == "krioukov_gpu" || "$queue" == "par-gpu-2" ]] ; then
    ncores=48
  elif [[ "$queue" == "par-gpu" ]] ; then
    ncores=32
  else
    ncores=0
  fi

  ./lsf/wrapper/causet_bat --start $job --readjob $readjob --ncores $ncores --flags '--spacetime '"$spacetime"' --nodes '"$nodes"' --age '"$age"' --link --core 1 --gpu --verbose -y --action smeared --print' --queue $queue --nsamples $samples --exclude $exclude
done

setnextjob $(($job+1))
