#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Account for billing
account=default

# Memory
memory=1gb

# GRES
gres=""

# Number of jobs to run in parallel in separate nodes
njobs=1

# Job ID offset (used for naming directories)
jobstart=1

# Number of samples to run serially on a single node
nsamples=1

# Job ID used for reading existing graph data
readjobid=0

# Graph ID used for reading existing graph data
readgraphid=0

# Flags passed to CausalSet program
flags=''

# SLURM partition
partition=''

# Number of nodes
nnodes=1

# Number of tasks
ntasks=1

# Number of cores per node
ncores=1

# Dependency
waitid=""

# Nodes excluded
exclude="c1065"

# Constraints on CPUs
constraint=""

# Parse command line parameters
OPTIONS=`getopt -o a:C:c:f:G:g:hJ:j:m:n:p:R:s:w:x: -l account:,ncores:,flags:,graph:,'help',nodes:,start:,njobs:,partition:,readjob:,nsamples:,waitfor:,exclude:,memory:,gres:,constraint:,tasks: -n 'causet_wrp' -- "$@"`

if [ $? -ne 0 ] ; then
  echo "Unrecognized option. Try running with --help flag." >&2
  exit 1
fi

eval set -- "$OPTIONS"

while true ; do
  case "$1" in
    -a|--account)
      case "$2" in
        "") shift 2 ;;
        *) account=$2 ; shift 2 ;;
      esac ;;
    -C|--constraint)
      case "$2" in
        "") shift 2 ;;
        *) constraint=$2 ; shift 2 ;;
      esac ;;
    -c|--ncores)
      case "$2" in
        "") shift 2 ;;
        *) ncores=$2 ; shift 2 ;;
      esac ;;
    -f|--flags)
      case "$2" in
        "") shift 2 ;;
        *) flags=$2 ; shift 2 ;;
      esac ;;
    -G|--graph)
      case "$2" in
        "") shift 2 ;;
        *) readgraphid=$2 ; shift 2 ;;
      esac ;;
    -g|--gres)
      case "$2" in
        "") shift 2 ;;
        *) gres=$2 ; shift 2 ;;
      esac ;;
    -J|--start)
      case "$2" in
        "") shift 2 ;;
        *) jobstart=$2 ; shift 2 ;;
      esac ;;
    -j|--njobs)
      case "$2" in
        "") shift 2 ;;
        *) njobs=$2 ; shift 2 ;;
      esac ;;
    -m|--memory)
      case "$2" in
        "") shift 2 ;;
        *) memory=$2 ; shift 2 ;;
      esac ;;
    -n|--nodes)
      case "$2" in
        "") shift 2 ;;
        *) nnodes=$2 ; shift 2 ;;
      esac ;;
    -p|--partition)
      case "$2" in
        "") shift 2 ;;
        *) partition=$2 ; shift 2 ;;
      esac ;;
    -R|--readjob)
      case "$2" in
        "") shift 2 ;;
        *) readjobid=$2; shift 2 ;;
      esac ;;
    -s|--nsamples)
      case "$2" in
        "") shift 2 ;;
        *) nsamples=$2 ; shift 2 ;;
      esac ;;
    -t|--tasks)
      case "$2" in
        "") shift 2 ;;
        *) ntasks=$2 ; shift 2 ;;
      esac ;;
    -w|--waitfor)
      case "$2" in
        "") shift 2 ;;
        *) waitid=$2 ; shift 2 ;;
      esac ;;
    -x|--exclude)
      case "$2" in
        "") shift 2 ;;
        *) exclude=$2 ; shift 2 ;;
      esac ;;
    -h|--help)
      echo "Usage: causet_wrp [OPTION]..."
      echo "Send CausalSet jobs to SLURM partitions."
      echo ""
      echo "  -a, --account    account for billing"
      echo "  -C, --constraint SLURM constraint"
      echo "  -c, --ncores     number of cores requested"
      echo "  -f, --flags      flags to pass to CausalSet program"
      echo "  -G, --graph      graph ID specified when reading a graph from another job"
      echo "  -g, --gres       generic resources (GRES)"
      echo "  -h, --help       display this help and exit"
      echo "  -J, --start      job ID offset, used for naming directories"
      echo "  -j, --njobs      number of jobs to run in parallel on separate nodes"
      echo "  -m, --memory     memory to allocate"
      echo "  -n, --nodes      number of nodes"
      echo "  -p, --partition  SLURM partition"
      echo "  -R, --readjob    job ID specified when reading graph(s) from another job"
      echo "  -s, --nsamples   number of samples to run serially on a single node"
      echo "  -t, --tasks      number of tasks"
      echo "  -w, --waitfor    job which must complete before this one starts"
      echo "  -x, --exclude    exclude a certain host"
      echo ""
      echo "Report bugs to wcunningham@perimeterinstitute.ca"
      echo "Bitbucket repository home page: <https://bitbucket.org/dk-lab/2015_code_causets>"
      exit 0 ;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 2 ;;
  esac
done

# Check if 'jobstart' is an integer or a string
num='^[0-9]+$' # Regular expression here
istart=1
notnumber=0 # Assume jobstart is a number by default
if ! [[ "$jobstart" =~ $num ]] ; then # Not a number
  njobs=1
  notnumber=1
else
  istart=$jobstart
fi

# Format wait statement
if [ "${waitid}" != "" ] ; then
  waitfor="SBATCH -d afterok\:${waitid}"
else
  waitfor=""
fi

# Send jobs to SLURM via sbatch
jobid=$jobstart
for (( i=${istart}; i<${njobs}+${istart}; i++ )) ; do
  if [ ${notnumber} -eq 0 ] ; then
    jobid=$i
  fi
  #if [[ ${readjobid} -ne 0 && ${readjobid} -eq ${jobid} ]] ; then
  #  echo "Invalid option: jobid equals readjobid!"
  #  exit 3;
  #fi
  mkdir -p $SCRATCH
  mkdir -p $SCRATCH/causet${jobid}
  sed "s:%flags%:$flags:g;s:%jobID%:$jobid:g;s:%nsamples%:$nsamples:g;s:%partition%:$partition:g;s:%ncores%:$ncores:g;s:%nnodes%:$nnodes:g;s:%readgraphid%:$readgraphid:g;s:%readjobid%:$readjobid:g;s:%waitfor%:$waitfor:g;s:%exclude%:$exclude:g;s:%account%:$account:g;s:%memory%:$memory:g;s:%gres%:$gres:g;s:%constraint%:$constraint:g;s:%ntasks%:$ntasks:g" < $CAUSET_HOME/cluster/slurm/batch/causet_$CLUSTERNAME | sbatch
  #sed "s:%flags%:$flags:g;s:%jobID%:$jobid:g;s:%nsamples%:$nsamples:g;s:%partition%:$partition:g;s:%ncores%:$ncores:g;s:%nnodes%:$nnodes:g;s:%readgraphid%:$readgraphid:g;s:%readjobid%:$readjobid:g;s:%waitfor%:$waitfor:g;s:%exclude%:$exclude:g;s:%account%:$account:g;s:%memory%:$memory:g;s:%gres%:$gres:g;s:%constraint%:$constraint:g;s:%ntasks%:$ntasks:g" < $CAUSET_HOME/cluster/slurm/batch/causet_$CLUSTERNAME > causet${jobid}.batch
  #exit 1
  sleep 1
done
