#!/bin/bash

###########################
#(C) Will Cunningham 2015 #
# Krioukov Research Group #
# Northeastern University #
###########################

# This is intended to be an example of how to launch 'lsf/causet_bat'

###########################
#  GENERATE NEW NETWORKS  #
###########################

#=================#
# No Acceleration #
#=================#

#./lsf/causet_bat --ncores 40 --flags '--nodes 124416 --age 0.01 --alpha 1.7998 --manifold f --link --verbose -y --print --success 62208' --start 184 --queue 'ser-par-10g-3' --nsamples 15

#./lsf/causet_bat --ncores 1 --flags '--nodes 1024 --age 1.5 --verbose -y --gen-ds-table --test' --start 59 --queue 'krioukov' --nsamples 1

#./lsf/causet_bat --ncores 1 --flags '--nodes 1024 --energy 0.5 --alpha 2 --manifold f --verbose -y --gen-flrw-table --test' --start 62 --queue 'krioukov' --nsamples 1

#==================#
# GPU Acceleration #
#==================#

# De Sitter
#./lsf/causet_bat --ncores 32 --flags '--nodes 330496 --age 0.5 --buffer 0.3 --symmetric --compact --link --verbose -y --gpu --print' --start 506 --queue 'par-gpu' --nsamples 10
#./lsf/causet_bat --ncores 32 --flags '--nodes 416256 --age 0.5 --buffer 0.3 --symmetric --compact --link --verbose -y --gpu --print' --start 507 --queue 'par-gpu' --nsamples 10
#./lsf/causet_bat --ncores 32 --flags '--nodes 524288 --age 0.5 --buffer 0.3 --symmetric --compact --link --verbose -y --gpu --print' --start 508 --queue 'par-gpu' --nsamples 10
#./lsf/causet_bat --ncores 32 --flags '--nodes 660736 --age 0.5 --buffer 0.3 --symmetric --compact --link --verbose -y --gpu --print' --start 509 --queue 'par-gpu' --nsamples 10
#./lsf/causet_bat --ncores 32 --flags '--nodes 832256 --age 0.5 --buffer 0.3 --symmetric --compact --link --verbose -y --gpu --print' --start 510 --queue 'par-gpu' --nsamples 10
#./lsf/causet_bat --ncores 32 --flags '--nodes 1048576 --age 0.5 --buffer 0.3 --symmetric --compact --link --verbose -y --gpu --print' --start 511 --queue 'par-gpu' --nsamples 10

# Dust
#./lsf/causet_bat --ncores 32 --flags '--nodes 342784 --age 4.6416 --alpha 15.4993 --manifold d --link --verbose -y --gpu --print --success 100000' --start 434 --queue 'par-gpu' --nsamples 3

# FLRW
#./lsf/causet_bat --ncores 32 --flags '--nodes 272896 --energy 0.92 --alpha 5.9999 --manifold f --link --verbose -y --gpu --print --success 10000000' --start 232 --queue 'par-gpu' --nsamples 10

#==================#
# MPI Acceleration #
#==================#

./lsf/causet_bat --ncores 16 --flags '--nodes 65536 --energy 0.7 --alpha 5 --manifold f --link --verbose -y' --start 510 --mpi 4 --queue 'ser-par-10g'

#=======================#
# GPU, MPI Acceleration #
#=======================#

#./lsf/causet_bat --ncores 32 --flags '--nodes 10240 --age 1.2 --buffer 0.3 --link --verbose -y --action 5 --seed 18100' --start 59 --mpi 2 --queue 'par-gpu' --nsamples 1

#./lsf/causet_bat --ncores 32 --flags '--nodes 10240 --energy 0.7 --alpha 3 --seed 18100 --manifold f --link --verbose -y --gpu --success 10240' --start 59 --mpi 4 --queue 'par-gpu' --nsamples 1

###########################
# STUDY EXISTING NETWORKS #
###########################

#=================#
# No Acceleration #
#=================#

#./lsf/causet_bat --ncores 1 --flags '--age 0.5 --compact --symmetric' --readjob 493 --start 512 --queue 'krioukov'

#./lsf/causet_bat --ncores 40 --flags '--age 1.5 --link --compact --verbose -y --distances 0.001' --graph 1425566890 --start 60 --queue 'ser-par-10g-3' --readjob 59

#./lsf/causet_bat --ncores 32 --flags '--energy 0.975 --alpha 5.9993 --manifold f --link --verbose -y --print --success 50000000' --graph 1440786261 --start '216S' --queue 'krioukov' --readjob 216 --nsamples 10

#==================#
# GPU Acceleration #
#==================#

#./lsf/causet_bat --ncores 32 --flags '--age 0.004 --alpha 1.999657 --manifold f --link --verbose -y --gpu --print --components' --graph 1440081852 --start '209S' --queue 'krioukov' --readjob 209

#==================#
# MPI Acceleration #
#==================#

#./lsf/causet_bat --ncores 40 --flags '--age 1.5 --link --compact --verbose -y --embedding 1 --print' --graph 1426166280 --start 62 --mpi 4 --queue 'ser-par-10g-2' --readjob 61

#./lsf/causet_bat --ncores 40 --flags '--age 1.5 --manifold f --link --compact --verbose -y --embedding 1 --print' --graph 1426105545 --start 60 --mpi 4 --queue 'ser-par-10g-2' --readjob 59
