#!/bin/bash

###########################
#(C) Will Cunningham 2015 #
# Krioukov Research Group #
# Northeastern University #
###########################

# Make sure base directories exist
mkdir -p /scratch/cunningham
mkdir -p /scratch/cunningham/causet@jobID@/

# Working directories
work=/scratch/cunningham/causet@jobID@
homedir=/home/cunningham.wi/projects/causets

# Copy the binary
cp $homedir/bin/CausalSet $work/

# Create peripheral directories and copy relevant files
mkdir -p $work/etc

cp $homedir/etc/degrees $work/etc/
cp $homedir/etc/deg_dist $work/etc/
cp $homedir/etc/components $work/etc/
cp $homedir/etc/confusion $work/etc/
cp $homedir/etc/clustering $work/etc/
cp $homedir/etc/clust_dist $work/etc/
cp $homedir/etc/fields $work/etc/
cp $homedir/etc/min_tau $work/etc/

cp $homedir/etc/raduc_table.cset.bin $work/etc/
cp $homedir/etc/ctuc_table.cset.bin $work/etc/
cp $homedir/etc/geodesics_flrw_table.cset.bin $work/etc/

cp $homedir/etc/mkdat $work/etc/

# Make directories to hold data files
$homedir/etc/mkdat $work

# Make sure directories exist if reading previously generated data
if [ @readjobid@ -ne 0 ] ; then
  dir1="/scratch/cunningham/causet@readjobid@"
  if [ ! -d ${dir1} ] ; then
    echo "Folder ${dir1} does not exist!"
    exit 1;
  fi

  dir2=$dir1/dat
  if [ ! -d ${dir2} ] ; then
    echo "Folder ${dir2} does not exist!"
    exit 2;
  fi

  dir3=$dir2/pos
  if [ ! -d ${dir3} ] ; then
    echo "Folder ${dir3} does not exist!"
    exit 3;
  fi

  posfile=$dir3/@readgraphid@.cset.pos.dat
  if [ ! -f ${posfile} ] ; then
    echo "Node position file ${posfile} does not exist!"
    exit 4;
  fi

  dir4=$dir2/edg
  if [ ! -d ${dir4} ] ; then
    echo "Folder ${dir4} does not exist!"
    exit 5;
  fi

  edgfile=$dir4/@readgraphid@.cset.edg.dat
  if [ ! -f ${edgfile} ] ; then
    echo "Edge list file ${edgfile} does not exist!"
    exit 6;
  fi

  # If the files exist then move the relevant data
  cp $posfile $work/dat/pos/
  cp $edgfile $work/dat/edg/
fi
