#!/bin/bash

njobs=1

if [ "$#" -eq 1 ]; then
  njobs=$1
fi

if [ $njobs -lt 1 ] || [ $njobs -gt 4 ]; then
  echo "Invalid number of jobs!"
  exit 1
fi

flags="--universe --age 4.0 --nodes 10240 --delta 1 --radius 1 --print --verbose -y --gpu --link"

sed "s:%flags%:$flags:g" < lsf/causet | bsub

if [ $njobs -gt 1 ]; then
  sleep 1
  sed "s:%flags%:$flags:g" < lsf/causet | bsub
fi

if [ $njobs -gt 2 ]; then
  sleep 1
  sed "s:%flags%:$flags:g" < lsf/causet | bsub
fi

if [ $njobs -gt 3 ]; then
  sleep 1
  sed "s:%flags%:$flags:g" < lsf/causet | bsub
fi

echo "Submitted ${njobs} Job(s) Successfully."
