#!/bin/bash

causets1=/scratch/cunningham/causets
causets2=/scratch/cunningham/causets2
causets3=/scratch/cunningham/causets3
causets4=/scratch/cunningham/causets4

if [ ! -d $causets1 ]; then
  echo "Primary folder does not exist!"
  exit 1
fi

mv $causets1/etc/data_keys.cset.key $causets1/etc/data_keys1.cset.key

if [ -d $causets2/dat ]; then
  mv $causets2/dat/*.cset.out $causets1/dat/
  mv $causets2/dat/cdk/*.dat $causets1/dat/cdk/
  mv $causets2/dat/cls/*.dat $causets1/dat/cls/
  mv $causets2/dat/dst/*.dat $causets1/dat/dst/
  mv $causets2/dat/edg/*.dat $causets1/dat/edg/
  mv $causets2/dat/emb/*.dat $causets1/dat/emb/
  mv $causets2/dat/emb/fp/*.dat $causets1/dat/emb/fp/
  mv $causets2/dat/emb/tn/*.dat $causets1/dat/emb/tn/
  mv $causets2/dat/idd/*.dat $causets1/dat/idd/
  mv $causets2/dat/idf/*.dat $causets1/dat/idf/
  mv $causets2/dat/odd/*.dat $causets1/dat/odd/
  mv $causets2/dat/odf/*.dat $causets1/dat/odf/
  mv $causets2/dat/pos/*.dat $causets1/dat/pos/

  mv $causets2/etc/data_keys.cset.key $causets1/etc/data_keys2.cset.key
fi

if [ -d $causets3/dat ]; then
  mv $causets3/dat/*.cset.out $causets1/dat/
  mv $causets3/dat/cdk/*.dat $causets1/dat/cdk/
  mv $causets3/dat/cls/*.dat $causets1/dat/cls/
  mv $causets3/dat/dst/*.dat $causets1/dat/dst/
  mv $causets3/dat/edg/*.dat $causets1/dat/edg/
  mv $causets3/dat/emb/*.dat $causets1/dat/emb/
  mv $causets3/dat/emb/fp/*.dat $causets1/dat/emb/fp/
  mv $causets3/dat/emb/tn/*.dat $causets1/dat/emb/tn/
  mv $causets3/dat/idd/*.dat $causets1/dat/idd/
  mv $causets3/dat/idf/*.dat $causets1/dat/idf/
  mv $causets3/dat/odd/*.dat $causets1/dat/odd/
  mv $causets3/dat/odf/*.dat $causets1/dat/odf/
  mv $causets3/dat/pos/*.dat $causets1/dat/pos/

  mv $causets3/etc/data_keys.cset.key $causets1/etc/data_keys3.cset.key
fi

if [ -d $causets4/dat ]; then
  mv $causets4/dat/*.cset.out $causets1/dat/
  mv $causets4/dat/cdk/*.dat $causets1/dat/cdk/
  mv $causets4/dat/cls/*.dat $causets1/dat/cls/
  mv $causets4/dat/dst/*.dat $causets1/dat/dst/
  mv $causets4/dat/edg/*.dat $causets1/dat/edg/
  mv $causets4/dat/emb/*.dat $causets1/dat/emb/
  mv $causets4/dat/emb/fp/*.dat $causets1/dat/emb/fp/
  mv $causets4/dat/emb/tn/*.dat $causets1/dat/emb/tn/
  mv $causets4/dat/idd/*.dat $causets1/dat/idd/
  mv $causets4/dat/idf/*.dat $causets1/dat/idf/
  mv $causets4/dat/odd/*.dat $causets1/dat/odd/
  mv $causets4/dat/odf/*.dat $causets1/dat/odf/
  mv $causets4/dat/pos/*.dat $causets1/dat/pos/

  mv $causets4/etc/data_keys.cset.key $causets1/etc/data_keys4.cset.key
fi

cat $causets1/etc/data_keys* > $causets1/etc/data_keys.cset.key

rm -rf $causets2
rm -rf $causets3
rm -rf $causets4
