#!/bin/bash

###########################
#(C) Will Cunningham 2014 #
# Krioukov Research Group #
# Northeastern University #
###########################

# Concatenates multiple jobs into a single folder

njobs=0
start_idx=1

if [ "$#" -lt 1 ]; then
  echo "Specify the number of jobs to concatenate!"
  exit 1
fi

njobs=$1

if [ "$#" -eq 2 ]; then
  start_idx=$2
fi

homedir=/home/cunningham.wi/projects/causets
sdir=/scratch/cunningham
cdir=$sdir/causets
mkdir -p $cdir
$homedir/etc/mkdat $cdir
cp -r $homedir/etc $cdir/

for (( i=$start_idx; i<=$njobs; i++ )); do
  job=$sdir/causet$i
  if [ ! -d $job ]; then
    echo "Folder ${job} does not exist!"
    exit 2
  fi

  mv $job/dat/*.cset.out $cdir/dat/ 2> /dev/null
  mv $job/dat/cdk/*.dat $cdir/dat/cdk/ 2> /dev/null
  mv $job/dat/cls/*.dat $cdir/dat/cls/ 2> /dev/null
  mv $job/dat/dst/*.dat $cdir/dat/dst/ 2> /dev/null
  mv $job/dat/edg/*.dat $cdir/dat/edg/ 2> /dev/null
  mv $job/dat/emb/*.dat $cdir/dat/emb/ 2> /dev/null
  mv $job/dat/emb/fp/*.dat $cdir/dat/emb/fp/ 2> /dev/null
  mv $job/dat/emb/tn/*.dat $cdir/dat/emb/tn/ 2> /dev/null
  mv $job/dat/idd/*.dat $cdir/dat/idd/ 2> /dev/null
  mv $job/dat/idf/*.dat $cdir/dat/idf/ 2> /dev/null
  mv $job/dat/odd/*.dat $cdir/dat/odd/ 2> /dev/null
  mv $job/dat/odf/*.dat $cdir/dat/odf/ 2> /dev/null
  mv $job/dat/pos/*.dat $cdir/dat/pos/ 2> /dev/null
  mv $job/etc/data_keys.cset.key $cdir/etc/data_keys$i.cset.key 2> /dev/null
done

cat $cdir/etc/data_keys* > $cdir/etc/final_data_keys.cset.key
rm $cdir/etc/data_keys*
mv $cdir/etc/final_data_keys.cset.key $cdir/etc/data_keys.key

#for (( i=$start_idx; i<=$njobs; i++ )); do
#  rm -rf $sdir/causet$i
#done
