#!/bin/bash

###########################
#(C) Will Cunningham 2015 #
# Krioukov Research Group #
# Northeastern University #
###########################

# This is intended to be an example of how to launch 'lsf/mbat'
#
# NOTE: To use Mathematica on Discovery the following lines should be added to your ~/.bashrc
#
# module load gnu-4.4-compilers
# module load fftw-3.3.3
# module load platform-mpi
# module load oracle_java_1.7u40
# module load mathematica-9
#
# These module names are accurate as of 18 Feb 2015.  Run 'module whatis mathematica-9' to find an up-to-date list of module requirements.

#------------------------#
# Average Degree in FLRW #
#------------------------#

#./lsf/mbat --name 'avg_deg_math' --ncores 1

#---------------------#
# de Sitter Geodesics #
#---------------------#

./lsf/mbat --name 'de_sitter_geodesics' --ncores 33

#---------------------------------#
# Puiseux Expansion for Geodesics #
#---------------------------------#

#./lsf/mbat --name 'puiseux_geodesics' --ncores 33
