#!/bin/bash

###########################
#(C) Will Cunningham 2015 #
# Krioukov Research Group #
# Northeastern University #
###########################

# This is intended to be an example of how to launch 'lsf/cbat'

###########################
#  GENERATE NEW NETWORKS  #
###########################

#=================#
# No Acceleration #
#=================#

#./lsf/cbat --ncores 40 --flags '--universe --nodes 131072 --degrees 10 --delta 500 --radius 0.8 --link --verbose -y --print --compact' --start 51 --queue 'ser-par-10g-3' --nsamples 10

#==================#
# GPU Acceleration #
#==================#

#./lsf/cbat --ncores 32 --flags '--universe --nodes 65536 --degrees 10 --delta 500 --radius 0.8 --link --verbose -y --compact --gpu --print' --start 59 --queue 'par-gpu' --nsamples 1

#=======================#
# GPU, MPI Acceleration #
#=======================#

#./lsf/cbat --ncores 32 --flags '--universe --nodes 131072 --degrees 10 --delta 500 --radius 0.7 --seed 18100 --link --compact --verbose -y --gpu --embedding 1' --start 51 --mpi 8 --queue 'par-gpu'

###########################
# STUDY EXISTING NETWORKS #
###########################

#=================#
# No Acceleration #
#=================#

#./lsf/cbat --ncores 16 --flags '--universe --degrees 10 --delta 500 --radius 0.8 --link --compact --verbose -y --success 0.001' --graph 1423781940 --start 60 --queue 'ser-par-10g' --readjob 59

#==================#
# MPI Acceleration #
#==================#

./lsf/cbat --ncores 40 --flags '--universe --degrees 10 --delta 500 --radius 0.8 --link --compact --verbose -y --success 0.001' --graph 1423781940 --start 60 --mpi 8 --queue 'ser-par-10g-2' --readjob 59
