#!/bin/bash

###########################
#(C) Will Cunningham 2017 #
#         DK Lab          #
# Northeastern University #
###########################

# Measure hub density of various manifolds

set -eu -o pipefail

# GENERAL USE
# Use 'setnextjob' command
# Set spacetime
# Set density/degree
# Choose queue
# Choose nodes and cutoffs

#spacetime=4800144
spacetime=5000182

#density=60
degree=10

if [ "$spacetime" -eq 4800114 ] || [ "$spacetime" -eq 5000182 ] ; then
  spacecut="radius"
else
  spacecut="alpha"
fi

if [[ -z ${degree+x} ]] ; then
  echo "Beginning constant density experiment."
  timecut="energy"
else
  echo "Beginning constant degree experiment."
  timecut="age"
fi

source /home/$USER/.queues
jobstart=$NEXT_JOB
samples=1
partition="krioukov_gpu"
ncores=$(sinfo -p $partition -o "%c" | awk 'NR==2 {print $1}')
exclude="compute-4-017"

if [ "$partition" = "par-gpu" ] || [ "$partition" = "par-gpu-2" ] || [ "$partition" = "par-gpu-3" ] || [ "$partition" = "krioukov_gpu" ] ; then
  gpu="--gpu"
else
  gpu=""
fi

nodes=1048576

#age=4.6416
#cutoff=1.684

age=1.0
cutoff=32.362

$CAUSET_HOME_DIR/slurm/wrapper/causet_wrp --start $jobstart --ncores $ncores --flags '--spacetime '"$spacetime"' --nodes '"$nodes"' --'"$timecut"' '"$age"' --'"$spacecut"' '"$cutoff"' --link '"$gpu"' --verbose -y --print --hubs 5000' --partition $partition --nsamples $samples --exclude $exclude

setnextjob $(($jobstart+1))
