#!/usr/bin/env python

###########################
#(C) Will Cunningham 2015 #
#         DK Lab          #
# Northeastern University #
###########################

# Used to calculate greedy routing parameters for the dust slab (constant q)

import math
import numpy as np
import sys

q = float(sys.argv[1])
omega = float(sys.argv[2])
alpha = 6

tau0 = (2.0/3.0)*np.arctanh(math.pow(omega, 0.5))
n0 = math.pi * q * math.pow(alpha * tau0, 3.0)

n1 = 256 * int(math.floor(n0 / 256))
alpha1 = math.pow(n1 / (math.pi * q), 1.0 / 3.0) / tau0

#sys.stdout.write('tau0:  %f\n' % tau0)
#sys.stdout.write('q:     %f\n' % q)
sys.stdout.write('N:     %d\n' % n1)
sys.stdout.write('alpha: %f\n' % alpha1)
