#!/usr/bin/env python

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

import math
import numpy as np
from scipy.integrate import quad, dblquad
import sys

if len(sys.argv) < 3:
	sys.stdout.write('Arguments are [average degree] [tau0] [number of nodes]\n')
	exit(1)

k = float(sys.argv[1])
tau0 = float(sys.argv[2])
n = int(sys.argv[3])

kappa = 108 * math.pi * dblquad(lambda x, y: pow(x * y, 2.0) * abs(pow(pow(x, 1.0 / 3.0) - pow(y, 1.0 / 3.0), 3.0)), 0, tau0, lambda x: 0, lambda x: tau0)[0] / pow(tau0, 3.0)
q = k / kappa
r = pow(n / (math.pi * q), 1.0 / 3.0) / tau0

sys.stdout.write('spatial cutoff: %f\n' % r)
