#!/usr/bin/env python

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Used to calculate greedy routing parameters for the dust diamond (constant q)

import math
import numpy as np
import sys

#q = 60
#tau0 = 0.85

q = float(sys.argv[1])
omega = float(sys.argv[2])
#tau0 = float(sys.argv[2])
tau0 = (2.0 / 3.0) * np.arctanh(math.pow(omega, 0.5))

mu = math.pow(1.5 * tau0, 4.0)
n = int(1981.0 * math.pi * q * mu / (2970.0 * 64.0))

sys.stdout.write('n: %d\n' % n)
