#!/usr/bin/env python

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

import math
import numpy as np
from scipy.integrate import quad, dblquad
import sys

if len(sys.argv) < 3:
	sys.stdout.write('Arguments are [average degree] [tau0] [number of nodes]\n')
	exit(1)

k = float(sys.argv[1])
tau0 = float(sys.argv[2])
n = int(sys.argv[3])

eta0 = -math.exp(-tau0)

kappa = -4.0 * math.pi * dblquad(lambda x, y: pow(abs(x - y), 3.0) / pow(x * y, 4.0), -1, eta0, lambda x: -1, lambda x: eta0)[0] / (1.0 + pow(eta0, -3.0))
q = k / kappa
r = pow(-9.0 * n / (4.0 * math.pi * q * (1.0 + pow(eta0, -3.0))), 1.0 / 3.0)

sys.stdout.write('spatial cutoff: %f\n' % r)
