#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Used to process output of many runs into a format Mathematica can read

set -eu -o pipefail

constq=true  #if false, constk=true
if [[ "$#" -lt 5 ]] ; then
  if [[ "$constq" == "true" ]] ; then
    echo "Arguments are [jobstart] [jobend] [density] [spacetime] [version]."
  else
    echo "Arguments are [jobstart] [jobend] [degree] [spacetime] [version]."
  fi
  exit 1
fi

jobstart=$1
jobend=$2
if [[ "$constq" == "true" ]] ; then
  q=$3
else
  k=$3
fi
st=$4
ver=$5

homedir=$CAUSET_HOME_DIR
#basedir='/krioukov/will'
basedir='/gss_gpfs_scratch/cunningham'

for i in $(seq ${jobstart} ${jobend}) ; do
  dir="$basedir/causet${i}"
  cd $dir
  logfile="CausalSet_Job-${i}_Sample-1.log"
  tau=$(cat $logfile | awk '/Max. Rescaled Time/ {print $5}')
  if [[ "$constq" == true ]] ; then
    degrees=$(cat $logfile | awk '/Expected Degrees/ {print $4}')
  else
    density=$(cat $logfile | awk '/Node Density/ {print $4}')
  fi
  success=$(etc/success | awk '/Success Ratio/')
  IFS=' ' read -r -a vals <<< "$success"
  sval=${vals[2]}
  serr=${vals[4]}

  if [[ "$constq" == true ]] ; then
    echo "$tau $degrees" >> $homedir/gr_degrees_q-${q}_${st}_${ver}.cset.dat.ref
    echo "$tau $sval $serr" >> $homedir/gr_success_q-${q}_${st}_${ver}.cset.dat.ref
  else
    echo "$tau $density" >> $homedir/gr_density_k-${k}_${st}_${ver}.cset.dat.ref
    echo "$tau $sval $serr" >> $homedir/gr_success_k-${k}_${st}_${ver}.cset.dat.ref
  fi
done
