#!/usr/bin/env python

###########################
#(C) Will Cunningham 2015 #
#         DK Lab          #
# Northeastern University #
###########################

# Used to calculate greedy routing parameters for the dust slab (constant k)

import math
import numpy as np
import sys

k = 10
tau0 = 0.2154
alpha = float(sys.argv[1])
kappa = 3.16526029e-04

omega = math.pow(math.tanh(1.5*tau0), 2)
q = k / kappa
n0 = math.pi * q * math.pow(alpha * tau0, 3)

n1 = 256 * int(math.floor(n0 / 256))
alpha1 = math.pow(n1 / (math.pi * q), 1.0 / 3.0) / tau0

sys.stdout.write('omega: %e\n' % omega)
sys.stdout.write('q:     %e\n' % q)
sys.stdout.write('N:     %d\n' % n1)
sys.stdout.write('alpha: %f\n' % alpha1)
