#!/usr/bin/env python

###########################
#(C) Will Cunningham 2015 #
#         DK Lab          #
# Northeastern University #
###########################

# Used to calculate greedy routing parameters for the flrw slab (constant q)

import math
import numpy as np
import sys

q = float(sys.argv[1])
omega = float(sys.argv[2])
alpha = 6

tau0 = (2.0/3.0)*np.arctanh(math.pow(omega, 0.5))

n0 = (2*math.pi/9)*q*math.pow(alpha, 3)*(math.sinh(3*tau0)-3*tau0)

n1 = 256 * int(math.floor(n0 / 256))
alpha1 = pow(n1 / ((2*math.pi/9)*q*(math.sinh(3*tau0)-3*tau0)), 1.0/3.0)

#sys.stdout.write('omega: %e\n' % omega)
#sys.stdout.write('tau0:  %f\n' % tau0)
#sys.stdout.write('q:     %e\n' % q)
sys.stdout.write('N:     %d\n' % n1)
sys.stdout.write('alpha: %f\n' % alpha1)
