#!/usr/bin/env python

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Generate a log-binned sequence of times and numbers of nodes

import numpy as np
import sys

if len(sys.argv) < 3:
	sys.stdout.write('Arguments are [tau_min] [tau_max] [min_nodes] [max_nodes] [nbins].\n')
	sys.exit(1)

tmin=float(sys.argv[1])
tmax=float(sys.argv[2])
nmin=int(sys.argv[3])
nmax=int(sys.argv[4])
nb=int(sys.argv[5])

times = np.logspace(np.log10(tmin), np.log10(tmax), num = nb)
nodes = np.logspace(np.log10(nmin), np.log10(nmax), num = nb)
vals = zip(times, nodes)
for val in vals:
	sys.stdout.write('%f %d\n' % (val[0], val[1]))
