#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Generate a raw data table for a constant-degree routing experiment

set -u -o pipefail

if [[ "$#" -lt 5 ]] ; then
  echo "Arguments are [jobstart] [jobend] [degree] [spacetime] [version]."
  exit 1
fi

jobstart=$1
jobend=$2
degree=$3
spacetime=$4
version=$5

declare -a tau
declare -a nodes
declare -a alpha
declare -a densities
declare -a success err
declare -a stretch err2

basedir='/gss_gpfs_scratch/cunningham'
homedir=$CAUSET_HOME_DIR

if [[ ! -d $basedir ]] ; then
  echo "Base directory does not exist!"
  exit 2
fi

for i in $(seq $jobstart $jobend) ; do
  dir=$basedir/causet${i}
  if [[ ! -d $dir ]] ; then
    echo "Could not find directory: $dir"
    exit 3
  fi

  cd $dir
  if [[ ! -e $dir/causet${i}.err ]] ; then
    echo "It appears job $i is still running."
    exit 4
  fi

  if [[ -s $dir/causet${i}.err ]] ; then
    echo "Error detected in job $i"
    cat $dir/causet${i}.err
    echo "Continue? [y/n]"
    read response
    if ! { [ "$response" == "y" ] || [ "$response" == "" ]; } ; then
      echo "Not continuing."
      exit 5
    fi
  fi

  nsamples=$(ls $dir/dat/*.cset.out 2> /dev/null | wc -l)
  if [[ $nsamples -eq 0 ]] ; then
    echo "No data found!"
    exit 6
  fi

  logfile=$dir/CausalSet_Job-${i}_Sample-1.log

  tau+=($(awk '/Max. Rescaled Time:/ {print $5}' $logfile))
  nodes+=($(awk '/Number of Nodes:/ {print $6}' $logfile))
  if [[ "$spacetime" -eq 4800114 ]] ; then
    alpha+=($(awk '/Spatial Cutoff:/ {print $4}' $logfile))
  else
    alpha+=($(awk '/Spatial Scaling:/ {print $4}' $logfile))
  fi
  densities+=($(awk '/Node Density:/ {print $4}' $logfile))
  s=($(./etc/success 1 | awk '/Success Ratio:/ {print $3, $5}'))
  success+=(${s[0]})
  err1+=(${s[1]})
  t=($(./etc/stretch | awk '/Stretch:/ {print $2, $4}'))
  stretch+=(${t[0]})
  err2+=(${t[1]})
done

outfile=$homedir/navigation_k-${degree}_${spacetime}_${version}.cset.suc.raw
echo "Job Time Nodes Cutoff Density Success Error Stretch Error" >> $outfile
njobs=$(($jobend-$jobstart+1))
for (( i=0 ; i<$njobs ; i++ )) ; do
  job=$(($i+$jobstart))
  echo "$job ${tau[$i]} ${nodes[$i]} ${alpha[$i]} ${densities[$i]} ${success[$i]} ${err1[$i]} ${stretch[$i]} ${err2[$i]}" >> $outfile
done
