#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Generate a raw data table for a constant-degree routing experiment

set -u -o pipefail

if [[ "$#" -lt 5 ]] ; then
  echo "Arguments are [jobstart] [jobend] [degree] [spacetime] [version]."
  exit 1
fi

jobstart=$1
jobend=$2
degree=$3
spacetime=$4
version=$5

declare -a times=(0.01 0.0278 0.0774 0.2154 0.5995 1.6681 4.6416)
declare -a nodes
declare -a alpha
declare -a densities
declare -a success err

basedir='/gss_gpfs_scratch/cunningham'
homedir='/home/cunningham.wi/projects/causets'

if [[ ! -d $basedir ]] ; then
  echo "Base directory does not exist!"
  exit 2
fi

for i in $(seq $jobstart $jobend) ; do
  dir=$basedir/causet${i}
  if [[ ! -d $dir ]] ; then
    echo "Could not find directory: $dir"
    exit 3
  fi

  cd $dir
  if [[ ! -e $dir/causet${i}.err ]] ; then
    echo "It appears job $i is still running."
    exit 6
  fi

  if [[ -s $dir/causet${i}.err ]] ; then
    echo "Error detected in job $i"
    echo "Continue? [y/n]"
    read response
    if [[ "$response" != "y" ]] ; then
      exit 5
    fi
  fi

  nsamples=$(ls $dir/dat/*.cset.out 2> /dev/null | wc -l)
  if [[ $nsamples -eq 0 ]] ; then
    echo "No data found!"
    exit 4
  fi

  logfile=$dir/CausalSet_Job-${i}_Sample-1.log

  nodes+=($(awk '/Number of Nodes:/ {print $6}' $logfile))
  alpha+=($(awk '/Spatial Scaling:/ {print $4}' $logfile))
  densities+=($(awk '/Node Density:/ {print $4}' $logfile))
  s=($(./etc/success | awk '/Success Ratio:/ {print $3, $5}'))
  success+=(${s[0]})
  err+=(${s[1]})
done

outfile=$homedir/navigation_k-${degree}_${spacetime}_${version}.cset.suc.raw
echo "Job Time Nodes Cutoff Density Success Error" >> $outfile
njobs=$(($jobend-$jobstart+1))
for (( i=0 ; i<$njobs ; i++ )) ; do
  job=$(($i+$jobstart))
  echo "$job ${times[$i]} ${nodes[$i]} ${alpha[$i]} ${densities[$i]} ${success[$i]} ${err[$i]}" >> $outfile
done
