#!/bin/bash

# Creates a parameter file which lsf/causet_test can read (for many runs)

#q=200000
q=$1

#omin=0.97
omin=$2
#omax=0.99
omax=$3
step=0.01

for i in $(seq ${omin} ${step} ${omax}) ; do
  echo "$i $(./etc/routing/gr_ds_diamond_q $q $i | awk '/n:/ {print $2}')" >> causet.par
done
