#!/bin/bash

# Creates a parameter file which lsf/causet_test can read (for several runs)

st=$1
k=$2
tau0=(0.01 0.0169865 0.028854 0.0490127 0.0832553 0.141421 0.240225 0.408057 0.693145 1.17741 1.99)
#tau0=(0.240225 0.408057 0.693145 1.17741 1.99)
#tau0=(0.028854)

basedir=./etc/routing
if [[ "$st" == 11300 ]] ; then
  scr=$basedir/gr_ds_diamond_k
elif [[ "$st" == 11332 ]] ; then
  scr=$basedir/gr_dust_diamond_k
elif [[ "$st" == 11396 ]] ; then
  scr=$basedir/gr_flrw_diamond_k
fi

for i in ${tau0[@]}; do
  echo "$i $($scr $k $i | awk '/n:/ {print $2}')" >> causet.par
done
