#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Creates a parameter file which lsf/causet_test can read (for several runs)

set -eu -o pipefail

if [[ "$#" -lt 5 ]] ; then
  echo "Arguments are [spacetime] [degree] [tmin] [tmax] [nbins]."
  exit 1
fi

st=$1
k=$2
tmin=$3
tmax=$4
nbins=$5

basedir=$CAUSET_HOME_DIR/etc/routing
#nmin=$((20000*$k))
nmin=200000
nmax=1048576

if [[ "$st" == 41508 ]] ; then
  scr=$basedir/gr_ds_slab_k
elif [[ "$st" == 41540 ]] ; then
  scr=$basedir/gr_dust_slab_k
elif [[ "$st" == 41604 ]] ; then
  scr=$basedir/gr_flrw_slab_k
fi

while IFS=' ' read -r -a vals ; do
  for (( i=0 ; i<${#vals[@]} ; i+=2 )) ; do
    echo "${vals[$i]} ${vals[$i+1]} $($scr $k ${vals[$i]} ${vals[$i+1]} | awk '/spatial cutoff/ {print $3}')" >> causet.par
  done
done <<< $($basedir/gr_params $tmin $tmax $nmin $nmax $nbins)
