#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

# Creates a parameter file which lsf/tests/navigation can read (for many runs)

st=$1
q=$2
omin=$3
omax=$4
step=0.01

basedir=./etc/routing
if [[ "$st" == 11300 ]] ; then
  scr=$basedir/gr_ds_diamond_q
elif [[ "$st" == 11332 ]] ; then
  scr=$basedir/gr_dust_diamond_q
elif [[ "$st" == 11396 ]] ; then
  scr=$basedir/gr_flrw_diamond_q
fi

for i in $(seq ${omin} ${step} ${omax}) ; do
  echo "$i $($scr $q $i | awk '/n:/ {print $2}')" >> causet.par
done
