#!/bin/bash

###########################
#(C) Will Cunningham 2014 #
#         DK Lab          #
# Northeastern University #
###########################

# The number of jobs to run in parallel in separate nodes
njobs=1

# The job ID offset (used for naming directories)
jobstart=1

# The number of samples to run serially on a single node
nsamples=1

# If reading a graph instead of generating one, specify the job number
readjobid=0

# If reading a graph instead of generating one, specify the graph id
readgraphid=0

# The flags to pass to the CausalSet program
flags=''

# LSF queue
queue=''

# Number of cores per node
ncores=1

# Use multiple nodes with MPI communication
mpinodes=0

# Wait for a job to finish first
waitid=0

exclude="none"

# Parse command line parameters
OPTIONS=`getopt -o c:f:G:hJ:j:m:q:R:s:w:x: -l ncores:,flags:,graph:,'help',mpi:,start:,njobs:,queue:,readjob:,nsamples:,waitfor:,exclude: -n 'causet_bat' -- "$@"`

if [ $? -ne 0 ] ; then
  echo "Unrecognized option. Try running with --help flag." >&2
  exit 1
fi

eval set -- "$OPTIONS"

while true ; do
  case "$1" in
    -c|--ncores)
      case "$2" in
        "") shift 2 ;;
        *) ncores=$2 ; shift 2 ;;
      esac ;;
    -f|--flags)
      case "$2" in
        "") shift 2 ;;
        *) flags=$2 ; shift 2 ;;
      esac ;;
    -G|--graph)
      case "$2" in
        "") shift 2 ;;
        *) readgraphid=$2 ; shift 2 ;;
      esac ;;
    -J|--start)
      case "$2" in
        "") shift 2 ;;
        *) jobstart=$2 ; shift 2 ;;
      esac ;;
    -j|--njobs)
      case "$2" in
        "") shift 2 ;;
        *) njobs=$2 ; shift 2 ;;
      esac ;;
    -m|--mpi)
      case "$2" in
        "") shift 2 ;;
        *) mpinodes=$2 ; shift 2 ;;
      esac ;;
    -q|--queue)
      case "$2" in
        "") shift 2 ;;
        *) queue=$2 ; shift 2 ;;
      esac ;;
    -R|--readjob)
      case "$2" in
        "") shift 2 ;;
        *) readjobid=$2; shift 2 ;;
      esac ;;
    -s|--nsamples)
      case "$2" in
        "") shift 2 ;;
        *) nsamples=$2 ; shift 2 ;;
      esac ;;
    -w|--waitfor)
      case "$2" in
        "") shift 2 ;;
        *) waitid=$2 ; shift 2 ;;
      esac ;;
    -x|--exclude)
      case "$2" in
        "") shift 2 ;;
        *) exclude=$2 ; shift 2 ;;
      esac ;;
    -h|--help)
      echo "Usage: causet_bat [OPTION]..."
      echo "Send CausalSet jobs to LSF queue on Discovery cluster."
      echo ""
      echo "  -c, --ncores     number of cores requested"
      echo "  -f, --flags      flags to pass to CausalSet program"
      echo "  -G, --graph      graph ID specified when reading a graph from another job"
      echo "  -h, --help       display this help and exit"
      echo "  -J, --start      job ID offset, used for naming directories"
      echo "  -j, --njobs      number of jobs to run in parallel on separate nodes"
      echo "  -m, --mpi        number of nodes allocated to MPI"
      echo "  -q, --queue      LSF queue"
      echo "  -R, --readjob    job ID specified when reading graph(s) from another job"
      echo "  -s, --nsamples   number of samples to run serially on a single node"
      echo "  -w, --waitfor    job which must complete before this one starts"
      echo "  -x, --exclude    exclude a certain host"
      echo ""
      echo "Report causet_bat bugs to w.cunningham@neu.edu"
      echo "Bitbucket repository home page: <https://bitbucket.org/dk-lab/2015_code_causets>"
      exit 0 ;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 2 ;;
  esac
done

# Check if 'jobstart' is an integer or a string
num='^[0-9]+$' # Regular expression here
istart=1
notnumber=0 # Assume jobstart is a number by default
if ! [[ "$jobstart" =~ $num ]] ; then # Not a number
  njobs=1
  notnumber=1
else
  istart=$jobstart
fi

# Check if MPI is being used
totalcores=$ncores
usempi=0
if [ ${mpinodes} -ne 0 ] ; then
  let totalcores=$ncores*$mpinodes
  usempi=1
fi

# Format wait statement
if [ ${waitid} -ne 0 ] ; then
  waitfor="BSUB -w done(CSET-${waitid})"
else
  waitfor=""
fi

# Send jobs to LSF via bsub
jobid=$jobstart
for (( i=${istart}; i<${njobs}+${istart}; i++ )) ; do
  if [ ${notnumber} -eq 0 ] ; then
    jobid=$i
  fi
  if [[ ${readjobid} -ne 0 && ${readjobid} -eq ${jobid} ]] ; then
    echo "Invalid option: jobid equals readjobid!"
    exit 3;
  fi
  sed "s:%flags%:$flags:g;s:%jobID%:$jobid:g;s:%nsamples%:$nsamples:g;s:%queue%:$queue:g;s:%ncores%:$ncores:g;s:%totalcores%:$totalcores:g;s:%mpinodes%:$mpinodes:g;s:%readgraphid%:$readgraphid:g;s:%readjobid%:$readjobid:g;s:%usempi%:$usempi:g;s:%waitfor%:$waitfor:g;s:%exclhost%:$exclude:g" < lsf/batch/causet_lsf | bsub
  sleep 1
done

#echo "Submitted ${njobs} Job(s) Successfully."
