#!/bin/bash

###########################
#(C) Will Cunningham 2015 #
#         DK Lab          #
# Northeastern University #
###########################

# The name of the job
jobname='myscript'

# Parse command line parameters
OPTIONS=`getopt -o hn: -l 'help',name: -n 'matlab_bat' -- "$@"`

if [ $? -ne 0 ] ; then
  echo "Unrecognized option. Try running with --help flag." >&2
  exit 1
fi

eval set -- "$OPTIONS"

while true ; do
  case "$1" in
    -n|--name)
      case "$2" in
        "") shift 2 ;;
        *) jobname=$2 ; shift 2 ;;
      esac ;;
    -h|--help)
      echo "Usage: matlab_bat [OPTION]..."
      echo "Send MATLAB jobs to LSF queue on Discovery cluster."
      echo ""
      echo "  -h, --help     display this help and exit"
      echo "  -n, --name     job name"
      echo ""
      echo "Report matlab_bat bugs to w.cunningham@neu.edu"
      echo "GitHub repository home page: <https://github.com/wjcunningham7/causets>"
      exit 0 ;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 2 ;;
  esac
done

# Send jobs to LSF via bsub
sed "s:%jobname%:$jobname:g" < lsf/batch/matlab_lsf | bsub
sleep 1

echo "Submitted MATLAB Job Successfully."
